### ISSUE TITLE
加载插件的问题

### ISSUE THREAD

**Issue by LcxAndroidwawa** [didi/VirtualAPK#10]
JNI_ERR returned from JNI_OnLoad in "/data/data/com.didi.virtualapk/.jiagu/libjiagu.so"

**Comment by LcxAndroidwawa** [comment]
这个问题搞定了 是我这个app是加固的 我不加固之后 可以成功的加载 但是我用 getPackageManager().getLaunchIntentForPackage(packageName);   获取到的intent是空的 希望解释一下

**Comment by LcxAndroidwawa** [comment]
现在用了框架内置的getLaunchIntent方法 但是又报了资源的错误
  Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x7f030034
                      at android.content.res.Resources.getValue(Resources.java:2325)
                      at android.content.res.Resources.loadXmlResourceParser(Resources.java:3688)
                      at android.content.res.Resources.getLayout(Resources.java:2141)
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:354)
                      at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:324)
                      at android.app.Activity.setContentView(Activity.java:1999)
                      at com.wondersgroup.qhrs.view.entrance.activity.WelcomeActivity.onCreate(WelcomeActivity.java:24)
                      at android.app.Activity.performCreate(Activity.java:5301)
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1094)
                      at com.didi.virtualapk.internal.VAInstrumentation.callActivityOnCreate(VAInstrumentation.java:141)
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2283)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2370) 
                      at android.app.ActivityThread.access$800(ActivityThread.java:155) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1243) 
                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                      at android.os.Looper.loop(Looper.java:136) 
                      at android.app.ActivityThread.main(ActivityThread.java:5426) 
                      at java.lang.reflect.Method.invokeNative(Native Method) 
                      at java.lang.reflect.Method.invoke(Method.java:515) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084) 
                      at dalvik.system.NativeStart.main(Native Method)

**Comment by singwhatiwanna** [comment]
@LcxAndroidwawa 插件的构建请参考：https://github.com/didi/VirtualAPK/wiki/Demo-%E5%B7%A5%E7%A8%8B%E8%BF%90%E8%A1%8C%E9%A1%BB%E7%9F%A5

**Comment by LcxAndroidwawa** [comment]
@singwhatiwanna 主席好 我不是运行的demo工程 我就是尝试加载一个完全外部的app

**Comment by singwhatiwanna** [comment]
@LcxAndroidwawa VirtualAPK不支持吊起一个外部的apk，插件apk需要通过我们的方式来构建才可以，仔细阅读wiki。
