### ISSUE TITLE
为什么项目中gradle和v7包的版本比较旧？使用v7-25.3.1解析dimension有bug

### ISSUE THREAD

**Issue by duqian291902259** [didi/VirtualAPK#101]
原项目使用的是
` compile 'com.android.support:appcompat-v7:22.2.0'`，怎么都编译不过，也没法install这个版本的库，升级了v7:25.3.1和gradle-3.3可以编译过，app和demo也能单独跑。但app中loadPlugin时crash了。
` E/AndroidRuntime: FATAL EXCEPTION: main
                                                                     Process: com.didi.virtualapk, PID: 14819
                                                                     java.lang.RuntimeException: Unable to resume activity {com.didi.virtualapk/com.didi.virtualapk.MainActivity}: java.lang.UnsupportedOperationException: Can't convert to dimension: type=0x1
                                                                         at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3353)
                                                                         at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3384)
                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
                                                                         at android.app.ActivityThread.access$900(ActivityThread.java:168)
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1393)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                         at android.os.Looper.loop(Looper.java:135)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5753)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at java.lang.reflect.Method.invoke(Method.java:372)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)
                                                                      Caused by: java.lang.UnsupportedOperationException: Can't convert to dimension: type=0x1
                                                                         at android.content.res.TypedArray.getDimensionPixelSize(TypedArray.java:584)
                                                                         at android.support.v7.app.WindowDecorActionBar.init(WindowDecorActionBar.java:232)
                                                                         at android.support.v7.app.WindowDecorActionBar.<init>(WindowDecorActionBar.java:176)
                                                                         at android.support.v7.app.AppCompatDelegateImplV9.initWindowDecorActionBar(AppCompatDelegateImplV9.java:188)
                                                                         at android.support.v7.app.AppCompatDelegateImplBase.getSupportActionBar(AppCompatDelegateImplBase.java:148)
                                                                         at android.support.v7.app.AppCompatDelegateImplV9.onPostResume(AppCompatDelegateImplV9.java:272)
                                                                         at android.support.v7.app.AppCompatActivity.onPostResume(AppCompatActivity.java:173)
                                                                         at android.app.Activity.performResume(Activity.java:6251)
                                                                         at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3342)
                                                                         at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3384) 
                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726) 
                                                                         at android.app.ActivityThread.access$900(ActivityThread.java:168) 
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1393) 
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                         at android.os.Looper.loop(Looper.java:135) 
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5753) 
                                                                         at java.lang.reflect.Method.invoke(Native Method) 
                                                                         at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405) 
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200) 
08-07 10:35:38.539 14819-14819/com.didi.virtualapk I/Process: Sending signal. PID: 14819 SIG: 9`

**Comment by XiuLin** [comment]
V7版本要和 CoreLibrary中保持一致。请按照官方要求的gradle版本进行构建

**Comment by superqiaopu** [comment]
同时在宿主工程和插件工程使用相同的更高版本的v7。
