### ISSUE TITLE
6.0申请权限崩溃

### ISSUE THREAD

**Issue by yanshili** [didi/VirtualAPK#109]
demo地址：https://github.com/yanshili/AppInfo.git
**plugin分支**
**用module依赖，v7包版本均改为24.2.1同样崩溃**
错误信息：
AndroidRuntime: FATAL EXCEPTION: main
                                                                Process: me.mooney.host, PID: 26795
                                                                java.lang.IllegalStateException: Could not execute method for android:onClick
                                                                    at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:293)
                                                                    at android.view.View.performClick(View.java:5646)
                                                                    at android.view.View$PerformClick.run(View.java:22459)
                                                                    at android.os.Handler.handleCallback(Handler.java:761)
                                                                    at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                    at android.os.Looper.loop(Looper.java:156)
                                                                    at android.app.ActivityThread.main(ActivityThread.java:6523)
                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)
                                                                 Caused by: java.lang.reflect.InvocationTargetException
                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                    at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:288)
                                                                    at android.view.View.performClick(View.java:5646) 
                                                                    at android.view.View$PerformClick.run(View.java:22459) 
                                                                    at android.os.Handler.handleCallback(Handler.java:761) 
                                                                    at android.os.Handler.dispatchMessage(Handler.java:98) 
                                                                    at android.os.Looper.loop(Looper.java:156) 
                                                                    at android.app.ActivityThread.main(ActivityThread.java:6523) 
                                                                    at java.lang.reflect.Method.invoke(Native Method) 
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941) 
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831) 
                                                                 Caused by: java.lang.AbstractMethodError: abstract method "java.lang.String android.content.pm.PackageManager.getPermissionControllerPackageName()"
                                                                    at android.content.pm.PackageManager.buildRequestPermissionsIntent(PackageManager.java:3393)
                                                                    at android.app.Activity.requestPermissions(Activity.java:4271)
                                                                    at android.support.v4.app.ActivityCompatApi23.requestPermissions(ActivityCompatApi23.java:45)
                                                                    at android.support.v4.app.ActivityCompat.requestPermissions(ActivityCompat.java:375)
                                                                    at me.mooney.plugin.PluginMainActivity.onMainClick(PluginMainActivity.java:39)
                                                                    at java.lang.reflect.Method.invoke(Native Method) 
                                                                    at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:288) 
                                                                    at android.view.View.performClick(View.java:5646) 
                                                                    at android.view.View$PerformClick.run(View.java:22459) 
                                                                    at android.os.Handler.handleCallback(Handler.java:761) 
                                                                    at android.os.Handler.dispatchMessage(Handler.java:98) 
                                                                    at android.os.Looper.loop(Looper.java:156) 
                                                                    at android.app.ActivityThread.main(ActivityThread.java:6523) 
                                                                    at java.lang.reflect.Method.invoke(Native Method) 
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941) 
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)

**Comment by XiuLin** [comment]
classpath 'com.android.tools.build:gradle:2.3.3'
change to
classpath 'com.android.tools.build:gradle:2.1.3'

**Comment by yanshili** [comment]
demo里就是2.1.3啊

**Comment by XiuLin** [comment]
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.3.3'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        jcenter()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

要诚实！！！！

**Comment by XiuLin** [comment]
还有 就是我们这个的确不支持在插件中申请权限

**Comment by yanshili** [comment]
plugin分支

**Comment by mqy1023** [comment]
插件app要动态申请权限，有什么解决方案了吗？
