### ISSUE TITLE
加载插件的时候提示java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity

### ISSUE THREAD

**Issue by MissBears** [didi/VirtualAPK#11]
Caused by: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
                                                       at android.support.v7.app.AppCompatDelegateImplBase.onCreate(AppCompatDelegateImplBase.java:122)
                                                       at android.support.v7.app.AppCompatDelegateImplV7.onCreate(AppCompatDelegateImplV7.java:146)
                                                       at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:59)
                                                       at com.didi.virtualapk.demo.aidl.BookManagerActivity.onCreate(BookManagerActivity.java:95)
                                                       at android.app.Activity.performCreate(Activity.java:6302)
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
                                                       at com.didi.virtualapk.internal.VAInstrumentation.callActivityOnCreate(VAInstrumentation.java:141)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2383)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2490) 
                                                       at android.app.ActivityThread.access$900(ActivityThread.java:153) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1358) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:148) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5456) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:735) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:625)

**Comment by singwhatiwanna** [comment]
@MissBears 插件的构建请参考：[Demo 工程运行须知](https://github.com/didi/VirtualAPK/wiki/Demo-%E5%B7%A5%E7%A8%8B%E8%BF%90%E8%A1%8C%E9%A1%BB%E7%9F%A5)

**Comment by lixinxinlove** [comment]
可能你的版本比较低吧！

**Comment by moziqi** [comment]
我也是类似的问题

**Comment by tokiii** [comment]
我也是类似的情况

**Comment by tokiii** [comment]
360马上也要开源rePlugin 了，看看哪个好用就用哪个吧

**Comment by xns1001** [comment]
plugindemo的BookManagerActivity是继承的AppCompatActivity,但是在manifest里面没有使用v7包的主题,把BookManagerActivity改成直接继承Activity就好了

**Comment by moziqi** [comment]
我连主题都删了，都不行了啊，我用FragmentActivity的啊

**Comment by chenenyu** [comment]
@moziqi @xns1001 @tokiii @MissBears 插件需要执行 `gradle assemblePlugin`任务来进行插件处理并生成apk, 不能用常规方式生成的apk让宿主去加载。
