### ISSUE TITLE
an error when onCreate

### ISSUE THREAD

**Issue by yaosongqwe** [didi/VirtualAPK#112]
FATAL EXCEPTION: main
                                                                               Process: com.wizarpos.wizarposmemberui, PID: 31926
                                                                               java.lang.RuntimeException: Unable to start activity ComponentInfo{com.wizarpos.wizarposmemberui/com.didi.virtualapk.core.A$1}: java.lang.NullPointerException
                                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2198)
                                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2248)
                                                                                   at android.app.ActivityThread.access$800(ActivityThread.java:138)
                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1199)
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                   at android.os.Looper.loop(Looper.java:136)
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5111)
                                                                                   at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                   at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:780)
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:596)
                                                                                   at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
                                                                                   at android.app.Activity.onCreate(Activity.java:903)
                                                                                   at android.support.v4.app.BaseFragmentActivityGingerbread.onCreate(BaseFragmentActivityGingerbread.java:51)
                                                                                   at android.support.v4.app.FragmentActivity.onCreate(FragmentActivity.java:319)
                                                                                   at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:88)
                                                                                   at com.ui.baseview.LogActivity.onCreate(LogActivity.java:17)
                                                                                   at com.ui.baseview.AbstractBaseViewActivity.onCreate(AbstractBaseViewActivity.java:46)
                                                                                   at com.ui.baseview.BaseViewActivity.onCreate(BaseViewActivity.java:10)
                                                                                   at com.wizarpos.pay.common.base.BaseViewActivity.onCreate(BaseViewActivity.java:42)
                                                                                   at com.wizarpos.activity.LoginMarketActivity.onCreate(LoginMarketActivity.java:51)
                                                                                   at android.app.Activity.performCreate(Activity.java:5231)
                                                                                   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
                                                                                   at com.didi.virtualapk.internal.VAInstrumentation.callActivityOnCreate(VAInstrumentation.java:141)
                                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2162)
                                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2248) 
                                                                                   at android.app.ActivityThread.access$800(ActivityThread.java:138) 
                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1199) 
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                   at android.os.Looper.loop(Looper.java:136) 
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5111) 
                                                                                   at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                                   at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:780) 
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:596) 
                                                                                   at dalvik.system.NativeStart.main(Native Method)

**Comment by XiuLin** [comment]
可能是 v7包的版本 在宿主中和插件中不一致导致的。官方的是一致的，但是很多开发者在导入工程后会根据android studio的提示进行升级，导致不一致的问题。

**Comment by superqiaopu** [comment]
同时在宿主工程和插件工程显式的依赖相同的v7。
