### ISSUE TITLE
小米1S手机 Android4.1.2 JZO54K 版本的执行demo中的插件崩溃，存在兼容性问题

### ISSUE THREAD

**Issue by laughy** [didi/VirtualAPK#113]
at java.lang.reflect.Method.invoke(Method.java:511) 
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560) 
                                                     at dalvik.system.NativeStart.main(Native Method) 
                                                  Caused by: android.content.ActivityNotFoundException: Unable to find explicit activity class {com.didi.virtualapk.demo/com.didi.virtualapk.demo.aidl.BookManagerActivity}; have you declared this activity in your AndroidManifest.xml?
                                                     at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1541)
                                                     at android.app.Instrumentation.execStartActivity(Instrumentation.java:1416)
                                                     at android.app.Activity.startActivityForResult(Activity.java:3427)
                                                     at android.app.Activity.startActivityForResult(Activity.java:3388)
                                                     at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:820)

**Comment by singwhatiwanna** [comment]
请问你这手机有刷过机吗？

**Comment by ByEric** [comment]
@laughy 同样的问题，请问怎么解决的

**Comment by Res2013** [comment]
@laughy 同样的问题，请问怎么解决的?

**Comment by 15189611** [comment]
@singwhatiwanna  我也遇到这个问题

**Comment by hprostudy** [comment]
@laughy 请问解决了吗？

**Comment by superqiaopu** [comment]
https://github.com/didi/VirtualAPK/wiki/%E6%8F%90%E9%97%AE%E5%BF%85%E7%9C%8B
