### ISSUE TITLE
启动一个插件，登录插件后，直接崩溃，报错，请大神帮我分析下

### ISSUE THREAD

**Issue by helloworkcupid** [didi/VirtualAPK#122]
Process: sg.zhihui.server, PID: 16758
                                                   java.lang.ExceptionInInitializerError
                                                       at org.eclipse.paho.android.service.MqttConnection.connect(MqttConnection.java:282)
                                                       at org.eclipse.paho.android.service.MqttService.connect(MqttService.java:316)
                                                       at org.eclipse.paho.android.service.MqttAndroidClient.doConnect(MqttAndroidClient.java:432)
                                                       at org.eclipse.paho.android.service.MqttAndroidClient.access$200(MqttAndroidClient.java:70)
                                                       at org.eclipse.paho.android.service.MqttAndroidClient$MyServiceConnection.onServiceConnected(MqttAndroidClient.java:107)
                                                       at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1284)
                                                       at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1301)
                                                       at android.os.Handler.handleCallback(Handler.java:739)
                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                       at android.os.Looper.loop(Looper.java:159)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5541)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:372)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:975)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)
                                                    Caused by: java.util.MissingResourceException: Can't find resource for bundle 'org.eclipse.paho.client.mqttv3.internal.nls.logcat_zh_CN', key ''
                                                       at java.util.ResourceBundle.missingResourceException(ResourceBundle.java:238)
                                                       at java.util.ResourceBundle.getBundle(ResourceBundle.java:230)
                                                       at java.util.ResourceBundle.getBundle(ResourceBundle.java:139)
                                                       at org.eclipse.paho.client.mqttv3.logging.LoggerFactory.getLogger(LoggerFactory.java:73)
                                                       at org.eclipse.paho.client.mqttv3.MqttAsyncClient.<clinit>(MqttAsyncClient.java:79)
                                                       at org.eclipse.paho.android.service.MqttConnection.connect(MqttConnection.java:282) 
                                                       at org.eclipse.paho.android.service.MqttService.connect(MqttService.java:316) 
                                                       at org.eclipse.paho.android.service.MqttAndroidClient.doConnect(MqttAndroidClient.java:432) 
                                                       at org.eclipse.paho.android.service.MqttAndroidClient.access$200(MqttAndroidClient.java:70) 
                                                       at org.eclipse.paho.android.service.MqttAndroidClient$MyServiceConnection.onServiceConnected(MqttAndroidClient.java:107) 
                                                       at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1284) 
                                                       at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1301) 
                                                       at android.os.Handler.handleCallback(Handler.java:739) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                       at android.os.Looper.loop(Looper.java:159) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5541) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at java.lang.reflect.Method.invoke(Method.java:372) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:975) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)

**Comment by singwhatiwanna** [comment]
看起来像是你们代码本身的bug
