### ISSUE TITLE
打插件包是否对插件包的applicationId有限制？

### ISSUE THREAD

**Issue by AriaLyy** [didi/VirtualAPK#126]
我使用demo提供的这个
```
defaultConfig {
    applicationId "com.didi.virtualapk.demo"
    minSdkVersion 15
    targetSdkVersion 15
    versionCode 1
    versionName "1.0"
    testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
  }
````
宿主可以正常运行插件的activity

但是，一旦我将 applicationId 替换成其它的包名
如：
```
defaultConfig {
    applicationId "com.waye.plugintestmain"
    minSdkVersion 15
    targetSdkVersion 15
    versionCode 1
    versionName "1.0"
    testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
  }
```
宿主运行插件时就会报activity没有注册mainfest的错误，以下是错误日志：
```
09-15 15:14:31.886 11065-11065/com.waye.plugintestmain E/InputEventSender: Exception dispatching finished signal.
09-15 15:14:31.886 11065-11065/com.waye.plugintestmain E/MessageQueue-JNI: Exception in MessageQueue callback: handleReceiveCallback
09-15 15:14:31.927 11065-11065/com.waye.plugintestmain E/MessageQueue-JNI: java.lang.IllegalStateException: Could not execute method of the activity
                                                                               at android.view.View$1.onClick(View.java:3856)
                                                                               at android.view.View.performClick(View.java:4471)
                                                                               at android.view.View.onKeyUp(View.java:8341)
                                                                               at android.widget.TextView.onKeyUp(TextView.java:5789)
                                                                               at android.view.KeyEvent.dispatch(KeyEvent.java:2703)
                                                                               at android.view.View.dispatchKeyEvent(View.java:7724)
                                                                               at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1446)
                                                                               at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1446)
                                                                               at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1446)
                                                                               at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1446)
                                                                               at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1446)
                                                                               at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1446)
                                                                               at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchKeyEvent(PhoneWindow.java:2104)
                                                                               at com.android.internal.policy.impl.PhoneWindow.superDispatchKeyEvent(PhoneWindow.java:1559)
                                                                               at android.app.Activity.dispatchKeyEvent(Activity.java:2453)
                                                                               at android.support.v7.internal.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:49)
                                                                               at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.dispatchKeyEvent(AppCompatDelegateImplBase.java:258)
                                                                               at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchKeyEvent(PhoneWindow.java:2031)
                                                                               at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:4306)
                                                                               at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4274)
                                                                               at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3828)
                                                                               at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3878)
                                                                               at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3847)
                                                                               at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3954)
                                                                               at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3855)
                                                                               at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4011)
                                                                               at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3828)
                                                                               at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3878)
                                                                               at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3847)
                                                                               at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3855)
                                                                               at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3828)
                                                                               at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3878)
                                                                               at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3847)
                                                                               at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3987)
                                                                               at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:4156)
                                                                               at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2080)
                                                                               at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:1757)
                                                                               at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:1748)
                                                                               at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:2057)
                                                                               at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
                                                                               at android.os.MessageQueue.nativePollOnce(Native Method)
                                                                               at android.os.MessageQueue.next(MessageQueue.java:138)
                                                                               at android.os.Looper.loop(Looper.java:150)
                                                                               at android.app.ActivityThread.main(ActivityThread.java:5312)
                                                                               at java.lang.reflect.Method.invokeNative(Native Method)
                                                                               at java.lang.reflect.Method.invoke(Method.java:515)
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:825)
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:641)
                                                                               at dalvik.system.NativeStart.main(Native Method)
                                                                            Caused by: java.lang.reflect.InvocationTargetException
                                                                               at java.lang.reflect.Method.invokeNative(Native Method)
                                                                               at java.lang.reflect.Method.invoke(Method.java:515)
                                                                               at android.view.View$1.onClick(View.java:3851)
                                                                               at android.view.View.performClick(View.java:4471) 
                                                                               at android.view.View.onKeyUp(View.java:8341) 
                                                                               at android.widget.TextView.onKeyUp(TextView.java:5789) 
                                                                               at android.view.KeyEvent.dispatch(KeyEvent.java:2703) 
                                                                               at android.view.View.dispatchKeyEvent(View.java:7724) 
                                                                               at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1446) 
                                                                               at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1446) 
                                                                               at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1446) 
                                                                               at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1446) 
                                                                               at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1446) 
                                                                               at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1446) 
                                                                               at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchKeyEvent(PhoneWindow.java:2104) 
                                                                               at com.android.internal.policy.impl.PhoneWindow.superDispatchKeyEvent(PhoneWindow.java:1559) 
                                                                               at android.app.Activity.dispatchKeyEvent(Activity.java:2453) 
                                                                               at android.support.v7.internal.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:49) 
                                                                               at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.dispatchKeyEvent(AppCompatDelegateImplBase.java:258) 
                                                                               at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchKeyEvent(PhoneWindow.java:2031) 
                                                                               at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:4306) 
                                                                               at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4274) 
                                                                               at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3828) 
                                                                               at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3878) 
                                                                               at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3847) 
                                                                               at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3954) 
                                                                               at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3855) 
                                                                               at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4011) 
                                                                               at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3828) 
                                                                               at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3878) 
                                                                               at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3847) 
                                                                               at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3855) 
                                                                               at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3828) 
                                                                               at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3878) 
                                                                               at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3847) 
                                                                               at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3987) 
                                                                               at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:4156) 
                                                                               at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2080) 
                                                                               at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:1757) 
                                                                               at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:1748) 
                                                                               at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:2057) 
                                                                               at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141) 
                                                                               at android.os.MessageQueue.nativePollOnce(Native Method) 
                                                                               at android.os.MessageQueue.next(MessageQueue.java:138) 
                                                                               at android.os.Looper.loop(Looper.java:150) 
                                                                               at android.app.ActivityThread.main(ActivityThread.java:5312) 
                                                                               at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                               at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:825) 
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:641) 
                                                                               at dalvik.system.NativeStart.main(Native Method) 
                                                                            Caused by: android.content.ActivityNotFoundException: Unable to find explicit activity class {c
09-15 15:14:31.928 11065-11065/com.waye.plugintestmain D/AndroidRuntime: Shutting down VM
09-15 15:14:31.928 11065-11065/com.waye.plugintestmain W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0x41ae2ce0)
09-15 15:14:31.928 11065-11065/com.waye.plugintestmain W/dalvikvm: threadid=1: uncaught exception occurred
09-15 15:14:31.928 11065-11065/com.waye.plugintestmain W/System.err: java.lang.IllegalStateException: Could not execute method of the activity
09-15 15:14:31.928 11065-11065/com.waye.plugintestmain W/System.err:     at android.view.View$1.onClick(View.java:3856)
09-15 15:14:31.928 11065-11065/com.waye.plugintestmain W/System.err:     at android.view.View.performClick(View.java:4471)
09-15 15:14:31.928 11065-11065/com.waye.plugintestmain W/System.err:     at android.view.View.onKeyUp(View.java:8341)
09-15 15:14:31.928 11065-11065/com.waye.plugintestmain W/System.err:     at android.widget.TextView.onKeyUp(TextView.java:5789)
09-15 15:14:31.929 11065-11065/com.waye.plugintestmain W/System.err:     at android.view.KeyEvent.dispatch(KeyEvent.java:2703)
09-15 15:14:31.929 11065-11065/com.waye.plugintestmain W/System.err:     at android.view.View.dispatchKeyEvent(View.java:7724)
09-15 15:14:31.929 11065-11065/com.waye.plugintestmain W/System.err:     at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1446)
09-15 15:14:31.929 11065-11065/com.waye.plugintestmain W/System.err:     at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1446)
09-15 15:14:31.930 11065-11065/com.waye.plugintestmain W/System.err:     at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1446)
09-15 15:14:31.930 11065-11065/com.waye.plugintestmain W/System.err:     at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1446)
09-15 15:14:31.930 11065-11065/com.waye.plugintestmain W/System.err:     at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1446)
09-15 15:14:31.930 11065-11065/com.waye.plugintestmain W/System.err:     at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1446)
09-15 15:14:31.930 11065-11065/com.waye.plugintestmain W/System.err:     at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchKeyEvent(PhoneWindow.java:2104)
09-15 15:14:31.930 11065-11065/com.waye.plugintestmain W/System.err:     at com.android.internal.policy.impl.PhoneWindow.superDispatchKeyEvent(PhoneWindow.java:1559)
09-15 15:14:31.931 11065-11065/com.waye.plugintestmain W/System.err:     at android.app.Activity.dispatchKeyEvent(Activity.java:2453)
09-15 15:14:31.931 11065-11065/com.waye.plugintestmain W/System.err:     at android.support.v7.internal.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:49)
09-15 15:14:31.932 11065-11065/com.waye.plugintestmain W/System.err:     at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.dispatchKeyEvent(AppCompatDelegateImplBase.java:258)
09-15 15:14:31.932 11065-11065/com.waye.plugintestmain W/System.err:     at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchKeyEvent(PhoneWindow.java:2031)
09-15 15:14:31.932 11065-11065/com.waye.plugintestmain W/System.err:     at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:4306)
09-15 15:14:31.933 11065-11065/com.waye.plugintestmain W/System.err:     at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4274)
09-15 15:14:31.933 11065-11065/com.waye.plugintestmain W/System.err:     at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3828)
09-15 15:14:31.933 11065-11065/com.waye.plugintestmain W/System.err:     at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3878)
09-15 15:14:31.933 11065-11065/com.waye.plugintestmain W/System.err:     at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3847)
09-15 15:14:31.933 11065-11065/com.waye.plugintestmain W/System.err:     at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3954)
09-15 15:14:31.933 11065-11065/com.waye.plugintestmain W/System.err:     at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3855)
09-15 15:14:31.933 11065-11065/com.waye.plugintestmain W/System.err:     at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4011)
09-15 15:14:31.933 11065-11065/com.waye.plugintestmain W/System.err:     at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3828)
09-15 15:14:31.933 11065-11065/com.waye.plugintestmain W/System.err:     at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3878)
09-15 15:14:31.934 11065-11065/com.waye.plugintestmain W/System.err:     at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3847)
09-15 15:14:31.937 11065-11065/com.waye.plugintestmain W/System.err:     at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3855)
09-15 15:14:31.937 11065-11065/com.waye.plugintestmain W/System.err:     at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3828)
09-15 15:14:31.937 11065-11065/com.waye.plugintestmain W/System.err:     at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3878)
09-15 15:14:31.937 11065-11065/com.waye.plugintestmain W/System.err:     at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3847)
09-15 15:14:31.937 11065-11065/com.waye.plugintestmain W/System.err:     at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3987)
09-15 15:14:31.937 11065-11065/com.waye.plugintestmain W/System.err:     at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:4156)
09-15 15:14:31.938 11065-11065/com.waye.plugintestmain W/System.err:     at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2080)
09-15 15:14:31.939 11065-11065/com.waye.plugintestmain W/System.err:     at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:1757)
09-15 15:14:31.944 11065-11065/com.waye.plugintestmain W/System.err:     at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:1748)
09-15 15:14:31.946 11065-11065/com.waye.plugintestmain W/System.err:     at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:2057)
09-15 15:14:31.946 11065-11065/com.waye.plugintestmain W/System.err:     at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
09-15 15:14:31.947 11065-11065/com.waye.plugintestmain W/System.err:     at android.os.MessageQueue.nativePollOnce(Native Method)
09-15 15:14:31.948 11065-11065/com.waye.plugintestmain W/System.err:     at android.os.MessageQueue.next(MessageQueue.java:138)
09-15 15:14:31.949 11065-11065/com.waye.plugintestmain W/System.err:     at android.os.Looper.loop(Looper.java:150)
09-15 15:14:31.949 11065-11065/com.waye.plugintestmain W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5312)
09-15 15:14:31.949 11065-11065/com.waye.plugintestmain W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
09-15 15:14:31.950 11065-11065/com.waye.plugintestmain W/System.err:     at java.lang.reflect.Method.invoke(Method.java:515)
09-15 15:14:31.950 11065-11065/com.waye.plugintestmain W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:825)
09-15 15:14:31.950 11065-11065/com.waye.plugintestmain W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:641)
09-15 15:14:31.950 11065-11065/com.waye.plugintestmain W/System.err:     at dalvik.system.NativeStart.main(Native Method)
09-15 15:14:31.950 11065-11065/com.waye.plugintestmain W/System.err: Caused by: java.lang.reflect.InvocationTargetException
09-15 15:14:31.953 11065-11065/com.waye.plugintestmain W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
09-15 15:14:31.953 11065-11065/com.waye.plugintestmain W/System.err:     at java.lang.reflect.Method.invoke(Method.java:515)
09-15 15:14:31.955 11065-11065/com.waye.plugintestmain W/System.err:     at android.view.View$1.onClick(View.java:3851)
09-15 15:14:31.955 11065-11065/com.waye.plugintestmain W/System.err: 	... 48 more
09-15 15:14:31.955 11065-11065/com.waye.plugintestmain W/System.err: Caused by: android.content.ActivityNotFoundException: Unable to find explicit activity class {com.waye.plugintestmain/com.waye.vrplugindemo.PMainActivity}; have you declared this activity in your AndroidManifest.xml?
09-15 15:14:31.961 11065-11065/com.waye.plugintestmain W/System.err:     at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1634)
09-15 15:14:31.962 11065-11065/com.waye.plugintestmain W/System.err:     at android.app.Instrumentation.execStartActivity(Instrumentation.java:1430)
09-15 15:14:31.962 11065-11065/com.waye.plugintestmain W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
09-15 15:14:31.962 11065-11065/com.waye.plugintestmain W/System.err:     at java.lang.reflect.Method.invoke(Method.java:515)
09-15 15:14:31.962 11065-11065/com.waye.plugintestmain W/System.err:     at com.didi.virtualapk.utils.ReflectUtil.invoke(ReflectUtil.java:86)
09-15 15:14:31.962 11065-11065/com.waye.plugintestmain W/System.err:     at com.didi.virtualapk.internal.VAInstrumentation.realExecStartActivity(VAInstrumentation.java:81)
09-15 15:14:31.962 11065-11065/com.waye.plugintestmain W/System.err:     at com.didi.virtualapk.internal.VAInstrumentation.execStartActivity(VAInstrumentation.java:67)
09-15 15:14:31.962 11065-11065/com.waye.plugintestmain W/System.err:     at android.app.Activity.startActivityForResult(Activity.java:3477)
09-15 15:14:31.962 11065-11065/com.waye.plugintestmain W/System.err:     at android.app.Activity.startActivityForResult(Activity.java:3431)
09-15 15:14:31.962 11065-11065/com.waye.plugintestmain W/System.err:     at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:820)
09-15 15:14:31.962 11065-11065/com.waye.plugintestmain W/System.err:     at android.app.Activity.startActivity(Activity.java:3680)
09-15 15:14:31.962 11065-11065/com.waye.plugintestmain W/System.err:     at android.app.Activity.startActivity(Activity.java:3648)
09-15 15:14:31.963 11065-11065/com.waye.plugintestmain W/System.err:     at com.waye.plugintestmain.MainActivity.startPluginActivity(MainActivity.java:45)
09-15 15:14:31.963 11065-11065/com.waye.plugintestmain W/System.err:     at com.waye.plugintestmain.MainActivity.onClick(MainActivity.java:26)
09-15 15:14:31.963 11065-11065/com.waye.plugintestmain W/System.err: 	... 51 more
09-15 15:14:31.963 11065-11065/com.waye.plugintestmain W/dalvikvm: threadid=1: calling UncaughtExceptionHandler
09-15 15:14:31.980 11065-11065/com.waye.plugintestmain E/AndroidRuntime: FATAL EXCEPTION: main
                                                                         Process: com.waye.plugintestmain, PID: 11065
                                                                         java.lang.IllegalStateException: Could not execute method of the activity
                                                                             at android.view.View$1.onClick(View.java:3856)
                                                                             at android.view.View.performClick(View.java:4471)
                                                                             at android.view.View.onKeyUp(View.java:8341)
                                                                             at android.widget.TextView.onKeyUp(TextView.java:5789)
                                                                             at android.view.KeyEvent.dispatch(KeyEvent.java:2703)
                                                                             at android.view.View.dispatchKeyEvent(View.java:7724)
                                                                             at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1446)
                                                                             at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1446)
                                                                             at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1446)
                                                                             at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1446)
                                                                             at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1446)
                                                                             at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1446)
                                                                             at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchKeyEvent(PhoneWindow.java:2104)
                                                                             at com.android.internal.policy.impl.PhoneWindow.superDispatchKeyEvent(PhoneWindow.java:1559)
                                                                             at android.app.Activity.dispatchKeyEvent(Activity.java:2453)
                                                                             at android.support.v7.internal.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:49)
                                                                             at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.dispatchKeyEvent(AppCompatDelegateImplBase.java:258)
                                                                             at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchKeyEvent(PhoneWindow.java:2031)
                                                                             at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:4306)
                                                                             at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4274)
                                                                             at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3828)
                                                                             at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3878)
                                                                             at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3847)
                                                                             at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3954)
                                                                             at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3855)
                                                                             at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4011)
                                                                             at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3828)
                                                                             at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3878)
                                                                             at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3847)
                                                                             at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3855)
                                                                             at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3828)
                                                                             at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3878)
                                                                             at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3847)
                                                                             at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3987)
                                                                             at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:4156)
                                                                             at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2080)
                                                                             at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:1757)
                                                                             at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:1748)
                                                                             at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:2057)
                                                                             at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
                                                                             at android.os.MessageQueue.nativePollOnce(Native Method)
                                                                             at android.os.MessageQueue.next(MessageQueue.java:138)
                                                                             at android.os.Looper.loop(Looper.java:150)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5312)
                                                                             at java.lang.reflect.Method.invokeNative(Native Method)
                                                                             at java.lang.reflect.Method.invoke(Method.java:515)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:825)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:641)
                                                                             at dalvik.system.NativeStart.main(Native Method)
                                                                          Caused by: java.lang.reflect.InvocationTargetException
                                                                             at java.lang.reflect.Method.invokeNative(Native Method)
                                                                             at java.lang.reflect.Method.invoke(Method.java:515)
                                                                             at android.view.View$1.onClick(View.java:3851)
                                                                             at android.view.View.performClick(View.java:4471) 
                                                                             at android.view.View.onKeyUp(View.java:8341) 
                                                                             at android.widget.TextView.onKeyUp(TextView.java:5789) 
                                                                             at android.view.KeyEvent.dispatch(KeyEvent.java:2703) 
                                                                             at android.view.View.dispatchKeyEvent(View.java:7724) 
                                                                             at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1446) 
                                                                             at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1446) 
                                                                             at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1446) 
                                                                             at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1446) 
                                                                             at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1446) 
                                                                             at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1446) 
                                                                             at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchKeyEvent(PhoneWindow.java:2104) 
                                                                             at com.android.internal.policy.impl.PhoneWindow.superDispatchKeyEvent(PhoneWindow.java:1559) 
                                                                             at android.app.Activity.dispatchKeyEvent(Activity.java:2453) 
                                                                             at android.support.v7.internal.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:49) 
                                                                             at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.dispatchKeyEvent(AppCompatDelegateImplBase.java:258) 
                                                                             at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchKeyEvent(PhoneWindow.java:2031) 
                                                                             at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:4306) 
                                                                             at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4274) 
                                                                             at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3828) 
                                                                             at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3878) 
                                                                             at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3847) 
                                                                             at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3954) 
                                                                             at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3855) 
                                                                             at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4011) 
                                                                             at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3828) 
                                                                             at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3878) 
                                                                             at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3847) 
                                                                             at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3855) 
                                                                             at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3828) 
                                                                             at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3878) 
                                                                             at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3847) 
                                                                             at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3987) 
                                                                             at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:4156) 
                                                                             at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2080) 
                                                                             at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:1757) 
                                                                             at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:1748) 
                                                                             at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:2057) 
                                                                             at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141) 
                                                                             at android.os.MessageQueue.nativePollOnce(Native Method) 
                                                                             at android.os.MessageQueue.next(MessageQueue.java:138) 
                                                                             at android.os.Looper.loop(Looper.java:150) 
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5312) 
                                                                             at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                             at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:825) 
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:641) 
                                                                             at dalvik.system.NativeStart.main(Native Method) 
                                                                          Caused by: android.content.Act
```

**Comment by pngfi** [comment]
目前需要applicationId 和mafiest文件中的package保持一致
