### ISSUE TITLE
Unable to start service com.didi.virtualapk.delegate.LocalService   ClassNotFoundException when unmarshalling: 

### ISSUE THREAD

**Issue by pngfi** [didi/VirtualAPK#128]
今天我更新了Corelibrary 为0.9.1，但是在Android5.1手机上 却报出如下错误，之前使用0.9.0版本的是没问这种问题的,测试两台5.1的手机上确认了该问题。
Android6.0也不会出现该问题，帮忙分析一下原因吧。

 CrashHandler: In thread: Thread[main,5,main]
                                                                             UncaughtException detected: java.lang.RuntimeException: Unable to start service com.didi.virtualapk.delegate.LocalService@1861d774 with Intent { cmp=xxx.xxx.xxx/com.didi.virtualapk.delegate.LocalService (has extras) }: android.os.BadParcelableException: ClassNotFoundException when unmarshalling: com.avos.avoscloud.im.v2.messages.AVIMTextMessage
                                                                                 at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3190)
                                                                                 at android.app.ActivityThread.access$2100(ActivityThread.java:188)
                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1578)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:111)
                                                                                 at android.os.Looper.loop(Looper.java:194)
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5739)
                                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                                 at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1039)
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:834)
                                                                              Caused by: android.os.BadParcelableException: ClassNotFoundException when unmarshalling: com.avos.avoscloud.im.v2.messages.AVIMTextMessage
                                                                                 at android.os.Parcel.readParcelableCreator(Parcel.java:2295)
                                                                                 at android.os.Parcel.readParcelable(Parcel.java:2245)
                                                                                 at android.os.Parcel.readValue(Parcel.java:2152)
                                                                                 at android.os.Parcel.readArrayMapInternal(Parcel.java:2485)
                                                                                 at android.os.BaseBundle.unparcel(BaseBundle.java:221)
                                                                                 at android.os.BaseBundle.getInt(BaseBundle.java:781)
                                                                                 at com.avos.avoscloud.PushService.processConversationEventsFromClient(PushService.java:572)
                                                                                 at com.avos.avoscloud.PushService.processIMRequests(PushService.java:210)
                                                                                 at com.avos.avoscloud.PushService.onStartCommand(PushService.java:180)
                                                                                 at com.didi.virtualapk.delegate.LocalService.onStartCommand(LocalService.java:112)
                                                                                 at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3173)
                                                                                 at android.app.ActivityThread.access$2100(ActivityThread.java:188) 
                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1578) 
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:111) 
                                                                                 at android.os.Looper.loop(Looper.java:194) 
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5739) 
                                                                                 at java.lang.reflect.Method.invoke(Native Method) 
                                                                                 at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                                 at

**Comment by singwhatiwanna** [comment]
@pngfi 0.9.1版本未曾对ClassLoader机制做改动，你再确认下。另外，Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.ClassLoader com.didi.virtualapk.internal.LoadedPlugin.getClassLoader()' on a null object reference
这个异常是怎么回事？为什么会空指针呢？

**Comment by pngfi** [comment]
@singwhatiwanna  主席好，我验证确实存在这样的问题。  上面的业务场景大概是我使用的LeanCloud的IM服务，发送消息时候要经过PushService，这时候找不到那个消息类AVIMTextMessage。确定0.9.0的版本不会出错，我能力有限实在找不到原因。

下面那个空指针不是问题所在，大概是因为程序Crash之前我启动了一个Actvity，从AMS回调回来之后程序已经崩溃了吧。

**Comment by pngfi** [comment]
关于这个问题，我再赘述一些。
1.其实0.9.0版本也是存在问题的，只是因为当时我在宿主和插件的mafiest文件中都声明了
<service android:name="com.avos.avoscloud.PushService" />
我发现0.9.1版本修改了queryIntentServices方法，
把 if (service.getComponentName().equals(component)) {
 修改为了  if (match(service, component)) {
根据0.9.0版本的策略这时候其实是相当于启动了宿主了中定义的pushservice，基本上还是走系统AMS启动流程，因此并没有任何异常。
而到0.9.1版本调整之后，因为现在插件中找到了符合的service，启动插件中定义的这个pushservice，走代理过程从LocalService中创建。
 
2.测试Android5.1版本会出现该问题，6.0不会（目前没有其他版本的测试机），具体原因不详

3.目前我的修改方法，
android.os.BadParcelableException: ClassNotFoundException when unmarshalling: com.avos.avoscloud.im.v2.messages.AVIMTextMessage
这个问题是因为在解包时候，不能从classLoader中找到对应的类，常见于intent传递数据到系统服务。
这里有一些关于这个问题的讨论
https://issuetracker.google.com/issues/36914697
目前我在Service创建时候，也就是修改LocalService的onStartCommand方法，添加一行
 target.setExtrasClassLoader(plugin.getClassLoader());

**Comment by singwhatiwanna** [comment]
@pngfi 你的描述我懂了，这个问题有时候在正常运行（不含插件）也会出现，你尝试下不含插件的情况下，是否还能重现？

**Comment by singwhatiwanna** [comment]
如果确实有问题，你可以把你的修改发送一个pr到dev分支。
