### ISSUE TITLE
小米4c，Android6.0，插件已经注册activity并且可以正常运行的情况下，仍找不到，什么原因？

### ISSUE THREAD

**Issue by ByEric** [didi/VirtualAPK#141]
FATAL EXCEPTION: main
                                                               Process: com.tvie.icar, PID: 12229
                                                               android.content.ActivityNotFoundException: Unable to find explicit activity class {com.test.virtualplugin/com.test.virtualplugin.PluginActivity}; have you declared this activity in your AndroidManifest.xml?
                                                                   at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1801)
                                                                   at android.app.Instrumentation.execStartActivity(Instrumentation.java:1514)
                                                                   at android.app.Activity.startActivityForResult(Activity.java:3978)
                                                                   at android.support.v4.app.BaseFragmentActivityJB.startActivityForResult(BaseFragmentActivityJB.java:54)
                                                                   at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:75)
                                                                   at android.app.Activity.startActivityForResult(Activity.java:3939)
                                                                   at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:708)
                                                                   at android.app.Activity.startActivity(Activity.java:4262)
                                                                   at android.app.Activity.startActivity(Activity.java:4230)

**Comment by XiuLin** [comment]
请按照官方构建流程进行，不能自行通过run的方式编译出插件。

**Comment by ByEric** [comment]
@XiuLin 是通过官方构建流程来的，插件apk并不是通过run的方式编译出

**Comment by Res2013** [comment]
同样碰到这个问题

**Comment by Mars212** [comment]
同样碰到这个问题  自己新建的demo  可以打开官方的image插件   用项目去打开image  就报上面那个错  不知道哪里冲突了

**Comment by hprostudy** [comment]
@Mars212 请问在Window下使用官方demo（0.9.0），assemblePlugin成功后加载插件也报这个错误是什么情况？     请问解决了吗？

**Comment by helloworkcupid** [comment]
这样多人，遇到类似问题，是不是有共性的地方呢？反复研究了官方流程，还是不行，郁闷啊！

**Comment by XiuLin** [comment]
看看是不是依赖的包有了版本上的冲突，如果没有，请使用dev分支.

**Comment by zhangyongfa888** [comment]
【已解决】
clean assembleRelease 有输出日志，有个提示 合并清单文件的警告，根据提示修改后就可以了~
项目太臃肿了~
