### ISSUE TITLE
用demo宿主启动插件的时候报java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.

### ISSUE THREAD

**Issue by lphgithub** [didi/VirtualAPK#162]
机型：huawei nxt-al10 android 7.0

AndroidRuntime: FATAL EXCEPTION: main
                                                                     Process: com.didi.virtualapk, PID: 29124
                                                                     java.lang.RuntimeException: Unable to start activity ComponentInfo{com.didi.virtualapk/com.didi.virtualapk.core.A$1}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2793)
                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2864)
                                                                         at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1567)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                         at android.os.Looper.loop(Looper.java:156)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:6523)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
                                                                      Caused by: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
                                                                         at android.support.v7.app.AppCompatDelegateImplBase.onCreate(AppCompatDelegateImplBase.java:122)
                                                                         at android.support.v7.app.AppCompatDelegateImplV7.onCreate(AppCompatDelegateImplV7.java:146)
                                                                         at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:59)
                                                                         at com.didi.virtualapk.demo.aidl.BookManagerActivity.onCreate(BookManagerActivity.java:95)
                                                                         at android.app.Activity.performCreate(Activity.java:6910)
                                                                         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1123)
                                                                         at com.didi.virtualapk.internal.VAInstrumentation.callActivityOnCreate(VAInstrumentation.java:145)
                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2746)
                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2864) 
                                                                         at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1567) 
                                                                         at android.os.Handler.dispatchMessage(Handler.java:105) 
                                                                         at android.os.Looper.loop(Looper.java:156) 
                                                                         at android.app.ActivityThread.main(ActivityThread.java:6523) 
                                                                         at java.lang.reflect.Method.invoke(Native Method) 
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942) 
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832) 
12-22 10:23:07.352 29124-29124/com.didi.virtualapk I/Process: Sending signal. PID: 29124 SIG: 9

**Comment by ihanbo** [comment]
三星s7 7.0同报

**Comment by XiuLin** [comment]
注意一下构建流程，还有依赖的库版本是否一致。
