### ISSUE TITLE
 have you declared this activity in your AndroidManifest.xml?

### ISSUE THREAD

**Issue by helloworkcupid** [didi/VirtualAPK#166]
android.content.ActivityNotFoundException: Unable to find explicit activity class {com.sg.zhui.serverhost/com.sg.zhui.entrance.MainActivityEn}; have you declared this activity in your AndroidManifest.xml?
                                                       at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1777)
                                                       at android.app.Instrumentation.execStartActivity(Instrumentation.java:1501)
                                                       at android.app.Activity.startActivityForResult(Activity.java:3863)
                                                       at android.app.Activity.startActivityForResult(Activity.java:3824)
                                                       at android.app.Activity.startActivity(Activity.java:4184)
                                                       at android.app.Activity.startActivity(Activity.java:4102)
                                                       at com.sg.zhui.serverhost.MyMainActivity$1.onClick(MyMainActivity.java:48)

你们遇到这样的问题吗？插件和宿主使用了相同的依赖 其他都没有问题，启动插件的时候，报了这个错
我是这样启动插件的：
                 Intent intent = new Intent();
                 intent.setClassName(MyMainActivity.this, "com.sg.zhui.entrance.MainActivityEn"); 
                startActivity(intent);
都是普通的activity 进行的测试，其他有依赖的还没有参与
谁解决了，望指教！

**Comment by XiuLin** [comment]
你看看你构建的流程和方式是否正确。还有使用最新的dev分支看看。

**Comment by helloworkcupid** [comment]
已解决

**Comment by imtianx** [comment]
@helloworkcupid 如何解决的，我也遇到这样的问题了，使用的 `dev`分支,
