### ISSUE TITLE
加载插件失败

### ISSUE THREAD

**Issue by akingyin1987** [didi/VirtualAPK#17]
java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.didi.virtualapk/com.didi.virtualapk.core.A$1}: java.lang.ClassNotFoundException: Didn't find class "com.didi.virtualapk.demo.aidl.BookManagerActivity" on path: DexPathList[[zip file "/storage/emulated/0/Test.apk"],nativeLibraryDirectories=[/data/data/com.didi.virtualapk/app_valibs, /vendor/lib, /system/lib]]
                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3002)
                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3273)
                                                                         at android.app.ActivityThread.access$1000(ActivityThread.java:219)
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1735)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                         at android.os.Looper.loop(Looper.java:145)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:6959)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at java.lang.reflect.Method.invoke(Method.java:372)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
                                                                      Caused by: java.lang.ClassNotFoundException: Didn't find class "com.didi.virtualapk.demo.aidl.BookManagerActivity" on path: DexPathList[[zip file "/storage/emulated/0/Test.apk"],nativeLibraryDirectories=[/data/data/com.didi.virtualapk/app_valibs, /vendor/lib, /system/lib]]
                                                                         at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                         at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                                         at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                                         at android.app.Instrumentation.newActivity(Instrumentation.java:1094)
                                                                         at com.didi.virtualapk.internal.VAInstrumentation.newActivity(VAInstrumentation.java:101)
                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2992)
                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3273) 
                                                                         at android.app.ActivityThread.access$1000(ActivityThread.java:219) 
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1735) 
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                         at android.os.Looper.loop(Looper.java:145) 
                                                                         at android.app.ActivityThread.main(ActivityThread.java:6959) 
                                                                         at java.lang.reflect.Method.invoke(Native Method) 
                                                                         at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404) 
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199) 
                                                                     	Suppressed: java.lang.ClassNotFoundException: Didn't find class "com.didi.virtualapk.demo.aidl.BookManagerActivity" on path: DexPathList[[zip file "/data/app/com.didi.virtualapk-2/base.apk", zip file "/data/app/com.didi.virtualapk-2/split_lib_dependencies_apk.apk", zip file "/data/app/com.didi.virtualapk-2/split_lib_slice_0_apk.apk", zip file "/data/app/com.didi.virtualapk-2/split_lib_slice_1_apk.apk", zip file "/data/app/com.didi.virtualapk-2/split_lib_slice_2_apk.apk", zip file "/data/app/com.didi.virtualapk-2/split_lib_slice_3_apk.apk", zip file "/data/app/com.didi.virtualapk-2/split_lib_slice_4_apk.apk", zip file "/data/app/com.didi.virtualapk-2/split_lib_slice_5_apk.apk", zip file "/data/app/com.didi.virtualapk-2/split_lib_slice_6_apk.apk", zip file "/data/app/com.didi.virtualapk-2/split_lib_slice_7_apk.apk", zip file "/data/app/com.didi.virtualapk-2/split_lib_slice_8_apk.apk", zip file "/data/app/com.didi.virtualapk-2/split_lib_slice_9_apk.apk", zip file "/storage/emulated/0/Test.apk"],nativeLibraryDirectories=[/data/app/com.didi.virtualapk-2/lib/arm, /vendor/lib, /system/lib, /data/data/com.didi.virtualapk/app_valibs]]
                                                                         at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                         at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                                         at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                                         		... 14 more
                                                                     		Suppressed: java.lang.ClassNotFoundException: com.didi.virtualapk.demo.aidl.BookManagerActivity
                                                                         at java.lang.Class.classForName(Native Method)
                                                                         at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                                         at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                                         at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                                         			... 15 more
                                                                      Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available

**Comment by ClaymanTwinkle** [comment]
+1

**Comment by akingyin1987** [comment]
另外核心里V7包是写死的 compile 'com.android.support:appcompat-v7:22.2.0'
导致会出现我用其他版本会有提示

**Comment by zhourihu5** [comment]
+1

**Comment by singwhatiwanna** [comment]
@akingyin1987 请阅读wiki
