### ISSUE TITLE
android.content.ActivityNotFoundException

### ISSUE THREAD

**Issue by zuoanguo** [didi/VirtualAPK#172]
Process: com.testapp, PID: 21878
                  android.content.ActivityNotFoundException: Unable to find explicit activity class {com.testapp/com.basedatadownload.MainCActivity}; have you declared this activity in your AndroidManifest.xml?
                      at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1628)
                      at android.app.Instrumentation.execStartActivity(Instrumentation.java:1424)
                      at java.lang.reflect.Method.invokeNative(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java:515)
                      at com.didi.virtualapk.utils.ReflectUtil.invoke(ReflectUtil.java:86)
                      at com.didi.virtualapk.internal.VAInstrumentation.realExecStartActivity(VAInstrumentation.java:81)
                      at com.didi.virtualapk.internal.VAInstrumentation.execStartActivity(VAInstrumentation.java:67)
                      at android.app.Activity.startActivityForResult(Activity.java:3424)
                      at android.support.v4.app.BaseFragmentActivityApi16.startActivityForResult(BaseFragmentActivityApi16.java:54)
                      at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:67)
                      at android.app.Activity.startActivityForResult(Activity.java:3385)
                      at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:732)
                      at android.app.Activity.startActivity(Activity.java:3643)
                      at android.app.Activity.startActivity(Activity.java:3611)
                      at com.testapp.MainCActivity.startPlugin(MainCActivity.java:94)
                      at com.testapp.MainCActivity.access$100(MainCActivity.java:15)
                      at com.testapp.MainCActivity$2.onClick(MainCActivity.java:35)
                      at android.view.View.performClick(View.java:4438)
                      at android.view.View$PerformClick.run(View.java:18422)
                      at android.os.Handler.handleCallback(Handler.java:733)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:136)
                      at android.app.ActivityThread.main(ActivityThread.java:5103)
                      at java.lang.reflect.Method.invokeNative(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java:515)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
                      at dalvik.system.NativeStart.main(Native Method)

是按照标准的构建流程来走的

**Comment by XiuLin** [comment]
一般出现这种问题就是没按照wiki构建流程来的。宿主./gradlew clean assembleRelease 
插件 ./gradlew clean assemblePlugin。

**Comment by mqy1023** [comment]
我这边将3.2改为3.1解决了
classpath 'com.android.tools.build:gradle:3.1.0'
