### ISSUE TITLE
startActivityUncheckedLocked

### ISSUE THREAD

**Issue by bluejuzz** [didi/VirtualAPK#174]
11-24 12:54:15.204 408-3126/system_process I/ActivityManager: START u0 {cmp=com.skylink.pdavender/com.didi.virtualapk.core.B$1 (has extras)} from pid 5045
11-24 12:54:15.204 408-3126/system_process V/ActivityManager: startActivityUncheckedLocked: task left null
                                                              java.lang.RuntimeException: here
                                                                  at com.android.server.am.ActivityStackSupervisor.startActivityUncheckedLocked(ActivityStackSupervisor.java:1662)
                                                                  at com.android.server.am.ActivityStackSupervisor.startActivityLocked(ActivityStackSupervisor.java:1265)
                                                                  at com.android.server.am.ActivityStackSupervisor.startActivityMayWait(ActivityStackSupervisor.java:744)
                                                                  at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:3153)
                                                                  at com.android.server.am.ActivityManagerService.startActivity(ActivityManagerService.java:3139)
                                                                  at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:135)
                                                                  at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2106)
                                                                  at android.os.Binder.execTransact(Binder.java:404)
                                                                  at dalvik.system.NativeStart.run(Native Method)

**Comment by juzzzzzzzzz** [comment]
随机性发生，打不开目标activity

**Comment by superqiaopu** [comment]
https://github.com/didi/VirtualAPK/wiki/%E6%8F%90%E9%97%AE%E5%BF%85%E7%9C%8B
