### ISSUE TITLE
点击加载插件崩溃

### ISSUE THREAD

**Issue by zouzhenglu** [didi/VirtualAPK#196]
如果寻找帮助请提供如下信息。
- VirtualAPK 运行相关：
1. core version
直接下载github上的代码，应该是0.9.4

2. 问题机型，系统版本
小米5X，MIUI9.5
3. 错误堆栈
`
03-22 10:31:24.364 12822-12822/com.didi.virtualapk E/AndroidRuntime: FATAL EXCEPTION: main
                                                                     Process: com.didi.virtualapk, PID: 12822
                                                                     java.lang.RuntimeException: Unable to start activity ComponentInfo{com.didi.virtualapk/com.didi.virtualapk.core.A$1}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2741)
                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2802)
                                                                         at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1549)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                         at android.os.Looper.loop(Looper.java:163)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:6379)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)
                                                                      Caused by: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
                                                                         at android.support.v7.app.AppCompatDelegateImplBase.onCreate(AppCompatDelegateImplBase.java:122)
                                                                         at android.support.v7.app.AppCompatDelegateImplV7.onCreate(AppCompatDelegateImplV7.java:146)
                                                                         at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:59)
                                                                         at com.didi.virtualapk.demo.aidl.BookManagerActivity.onCreate(BookManagerActivity.java:95)
                                                                         at android.app.Activity.performCreate(Activity.java:6875)
                                                                         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
                                                                         at com.didi.virtualapk.internal.VAInstrumentation.callActivityOnCreate(VAInstrumentation.java:145)
                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2694)
                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2802) 
                                                                         at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1549) 
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                         at android.os.Looper.loop(Looper.java:163) 
                                                                         at android.app.ActivityThread.main(ActivityThread.java:6379) 
                                                                         at java.lang.reflect.Method.invoke(Native Method) 
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904) 
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)  `
4. 复现步骤
下载源码，安装宿主apk，打包插件apk，将插件push进入手机，杀掉app，运行宿主apk，点击加载插件，崩溃
- VirtualAPK 构建相关：
1. gradle version
4.1
2. android gradle plugin version
        classpath 'com.android.tools.build:gradle:2.3.3'
3. VirtualAPK plugin version

eg：

  classpath 'com.didi.virtualapk:gradle:0.9.4'
4. OS type
  windows 10

**Comment by l8023lxb** [comment]
插件apk打包要用PluginDemo目录下的make.sh编译，或者手动输入命令./gradlew clean assemblePlugin编译，再把生成的apkpush到手机。

**Comment by superqiaopu** [comment]
https://github.com/didi/VirtualAPK/wiki/Demo-%E5%B7%A5%E7%A8%8B%E8%BF%90%E8%A1%8C%E9%A1%BB%E7%9F%A5
