### ISSUE TITLE
貌似找不到资源，怎么破

### ISSUE THREAD

**Issue by moziqi** [didi/VirtualAPK#20]
`FATAL EXCEPTION: main
                                                                   Process: com.didi.virtualapk, PID: 5887
                                                                   java.lang.RuntimeException: Unable to start activity ComponentInfo{com.didi.virtualapk/com.didi.virtualapk.core.A$1}: android.content.res.Resources$NotFoundException: Resource ID #0x7f03001a
                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2187)
                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2236)
                                                                       at android.app.ActivityThread.access$800(ActivityThread.java:138)
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1199)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                       at android.os.Looper.loop(Looper.java:136)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5095)
                                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                                       at java.lang.reflect.Method.invoke(Method.java:515)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:602)
                                                                       at dalvik.system.NativeStart.main(Native Method)
                                                                    Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x7f03001a
                                                                       at android.content.res.Resources.getValue(Resources.java:1123)
                                                                       at android.content.res.Resources.loadXmlResourceParser(Resources.java:2309)
                                                                       at android.content.res.Resources.getLayout(Resources.java:939)
                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:395)
                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
                                                                       at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:290)
                                                                       at android.app.Activity.setContentView(Activity.java:1929)
                                                                       at com.didi.virtualapk.demo.aidl.BookManagerActivity.onCreate(BookManagerActivity.java:98)
                                                                       at android.app.Activity.performCreate(Activity.java:5231)
                                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
                                                                       at com.didi.virtualapk.internal.VAInstrumentation.callActivityOnCreate(VAInstrumentation.java:141)
                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2151)
                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2236) 
                                                                       at android.app.ActivityThread.access$800(ActivityThread.java:138) 
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1199) 
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                       at android.os.Looper.loop(Looper.java:136) 
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5095) 
                                                                       at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                       at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786) 
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:602) 
                                                                       at dalvik.system.NativeStart.main(Native Method) `

**Comment by singwhatiwanna** [comment]
请提供更详细的信息

**Comment by moziqi** [comment]
我运行起来就这样了,我后面改成用纯代码写的布局,就不会,貌似R文件的资源找不到,不知道怎么处理

**Comment by singwhatiwanna** [comment]
@moziqi 请阅读wiki

**Comment by maolubin** [comment]
我也是这个问题07-11 09:24:39.036 29312-29312/com.didi.virtualapk E/AndroidRuntime: FATAL EXCEPTION: main
                                                                     Process: com.didi.virtualapk, PID: 29312
                                                                     java.lang.RuntimeException: Unable to start activity ComponentInfo{com.didi.virtualapk/com.didi.virtualapk.core.A$1}: android.content.res.Resources$NotFoundException: File 搜索 from xml type layout resource ID #0x7f060008
                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2484)
                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2544)
                                                                         at android.app.ActivityThread.access$900(ActivityThread.java:150)
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1394)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                         at android.os.Looper.loop(Looper.java:168)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5845)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:797)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:687)
                                                                      Caused by: android.content.res.Resources$NotFoundException: File 搜索 from xml type layout resource ID #0x7f060008
                                                                         at android.content.res.Resources.loadXmlResourceParser(Resources.java:2836)
                                                                         at android.content.res.Resources.loadXmlResourceParser(Resources.java:2791)
                                                                         at android.content.res.Resources.getLayout(Resources.java:1173)
                                                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:421)
                                                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
                                                                         at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:411)
                                                                         at android.app.Activity.setContentView(Activity.java:2177)
                                                                         at com.businesshall.activity.SplashActivity.onCreate(SplashActivity.java:30)
                                                                         at android.app.Activity.performCreate(Activity.java:6248)
                                                                         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1125)
                                                                         at com.didi.virtualapk.internal.VAInstrumentation.callActivityOnCreate(VAInstrumentation.java:141)
                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2437)
                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2544) 
                                                                         at android.app.ActivityThread.access$900(ActivityThread.java:150) 
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1394) 
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                         at android.os.Looper.loop(Looper.java:168) 
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5845) 
                                                                         at java.lang.reflect.Method.invoke(Native Method) 
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:797) 
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:687)
