### ISSUE TITLE
Crash on Android O

### ISSUE THREAD

**Issue by moshebe** [didi/VirtualAPK#207]
The library seems to be incompitible with Android O (also found comments on code that implied so)

Any expectations for fixing these issues ?

Thanks in advanced !

**Comment by UrielShimony** [comment]
+1

**Comment by superqiaopu** [comment]
Please show us the crash log and other info.

**Comment by moshebe** [comment]
First crash occurred on accessing signature field:

> E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.allen.virtualapkdemo, PID: 2887
                  java.lang.NoSuchFieldError: No instance field mSignatures of type [Landroid/content/pm/Signature; in class Landroid/content/pm/PackageParser$Package; or its superclasses (declaration of 'android.content.pm.PackageParser$Package' appears in /system/framework/framework.jar)
                      at com.didi.virtualapk.internal.LoadedPlugin.<init>(LoadedPlugin.java:155)
                      at com.didi.virtualapk.internal.LoadedPlugin.create(LoadedPlugin.java:78)
                      at com.didi.virtualapk.PluginManager.loadPlugin(PluginManager.java:202)
                      at com.allen.virtualapkdemo.MainActivity.loadPlugin(MainActivity.java:57)
                      at com.allen.virtualapkdemo.MainActivity.onCreate(MainActivity.java:30)
                      at android.app.Activity.performCreate(Activity.java:7117)
                      at android.app.Activity.performCreate(Activity.java:7108)
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1262)
                      at com.didi.virtualapk.internal.VAInstrumentation.callActivityOnCreate(VAInstrumentation.java:141)
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2867)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3027)
                      at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
                      at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:101)
                      at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:73)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1786)
                      at android.os.Handler.dispatchMessage(Handler.java:106)
                      at android.os.Looper.loop(Looper.java:164)
                      at android.app.ActivityThread.main(ActivityThread.java:6656)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)



Another one found with comment attached to the crashed function that implied on incompatibility with android O (as appear in the attached image) 

> W/zygote: JIT profile information will not be recorded: profile file does not exits.
I/chatty: uid=10089(com.allen.virtualapkdemo) identical 9 lines
W/zygote: JIT profile information will not be recorded: profile file does not exits.
I/MemoryIntArray: created from parcel MemoryIntArray@192774149 mMemoryAddr=3995029504 mFd=51
W/zygote: Verification of void com.allen.virtualapkdemo.MyApplication.attachBaseContext(android.content.Context) took 446.646ms
W/zygote: Accessing hidden field Landroid/app/ActivityThread;->sCurrentActivityThread:Landroid/app/ActivityThread; (light greylist, reflection)
          Accessing hidden method Landroid/app/ActivityThread;->getInstrumentation()Landroid/app/Instrumentation; (light greylist, reflection)
W/zygote: Accessing hidden field Landroid/app/ActivityThread;->mInstrumentation:Landroid/app/Instrumentation; (light greylist, reflection)
          Accessing hidden method Landroid/app/ActivityThread;->getHandler()Landroid/os/Handler; (light greylist, reflection)
          Accessing hidden field Landroid/os/Handler;->mCallback:Landroid/os/Handler$Callback; (light greylist, reflection)
W/System.err: java.lang.NoSuchFieldException: No field gDefault in class Landroid/app/ActivityManagerNative; (declaration of 'android.app.ActivityManagerNative' appears in /system/framework/framework.jar)
W/System.err:     at java.lang.Class.getDeclaredField(Native Method)
W/System.err:     at com.didi.virtualapk.utils.ReflectUtil.getField(ReflectUtil.java:36)
                  at com.didi.virtualapk.PluginManager.hookSystemServices(PluginManager.java:116)
W/System.err:     at com.didi.virtualapk.PluginManager.prepare(PluginManager.java:95)
W/System.err:     at com.didi.virtualapk.PluginManager.<init>(PluginManager.java:89)
W/System.err:     at com.didi.virtualapk.PluginManager.getInstance(PluginManager.java:75)
W/System.err:     at com.allen.virtualapkdemo.MyApplication.attachBaseContext(MyApplication.java:20)
W/System.err:     at android.app.Application.attach(Application.java:200)
W/System.err:     at android.app.Instrumentation.newApplication(Instrumentation.java:1121)
W/System.err:     at android.app.LoadedApk.makeApplication(LoadedApk.java:998)
W/System.err:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5845)
W/System.err:     at android.app.ActivityThread.access$1100(ActivityThread.java:193)
W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1623)
W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:106)
W/System.err:     at android.os.Looper.loop(Looper.java:164)
W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6656)
W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)
I/InstantRun: starting instant run server: is main process
W/zygote: Verification of void com.allen.virtualapkdemo.MainActivity.initView() took 127.172ms
W/zygote: Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (light greylist, reflection)
          Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (light greylist, reflection)

**Comment by superqiaopu** [comment]
VirtualApk has some problem in Android P Preview. We are working hard to be compatible with Android P. 

Please follow the newer commit at dev branch in future.

**Comment by superqiaopu** [comment]
Please try com.didi.virtualapk:core:0.9.7-dev.
