### ISSUE TITLE
java.lang.RuntimeException: Unable to start activity ComponentInfo 无法启动插件问题

### ISSUE THREAD

**Issue by StudyLifeTime** [didi/VirtualAPK#208]
- VirtualAPK 运行相关：

1. core version
```
   compile 'com.didi.virtualapk:core:0.9.1'
```
2. 问题机型，系统版本

魅蓝node 5     7.0 系统

3. 完整log
###  编译 宿主
```

#脚本
./gradlew clean assembleRelease
adb install app/build/outputs/apk/release/app-release.apk

# 编译日志
> Configure project :app
Configuration 'compile' in project ':app' is deprecated. Use 'implementation' instead.

> Task :app:compileReleaseJavaWithJavac
Used compileClasspath: releaseCompileClasspath


BUILD SUCCESSFUL in 4s
28 actionable tasks: 27 executed, 1 up-to-date
Success

```
### 编译插件

```
# 编译脚本
./gradlew clean assemblePlugin
adb push app/build/outputs/apk/release/app-release.apk /sdcard/Test.apk

# 编译日志

> Task :app:processReleaseManifest
Stripped manifest of artifact: AndroidManifest.xml (com.android.support:appcompat-v7:26.1.0) -> /Users/Jalen/.gradle/caches/transforms-1/files-1.1/appcompat-v7-26.1.0.aar/48e73afb10bf45ecb81b09a5df79d77e/AndroidManifest.xml
Stripped manifest of artifact: AndroidManifest.xml (com.android.support:animated-vector-drawable:26.1.0) -> /Users/Jalen/.gradle/caches/transforms-1/files-1.1/animated-vector-drawable-26.1.0.aar/412501fe842f9ebba87ce7b1c86441c8/AndroidManifest.xml
Stripped manifest of artifact: AndroidManifest.xml (com.android.support:support-vector-drawable:26.1.0) -> /Users/Jalen/.gradle/caches/transforms-1/files-1.1/support-vector-drawable-26.1.0.aar/585d84399fccccaec48d46c4b3df3f0d/AndroidManifest.xml
Stripped manifest of artifact: AndroidManifest.xml (com.android.support:support-v4:26.1.0) -> /Users/Jalen/.gradle/caches/transforms-1/files-1.1/support-v4-26.1.0.aar/8c93c1720634fb0dce81c96b2dc658a5/AndroidManifest.xml
Stripped manifest of artifact: AndroidManifest.xml (com.android.support:support-media-compat:26.1.0) -> /Users/Jalen/.gradle/caches/transforms-1/files-1.1/support-media-compat-26.1.0.aar/248332f86284791f967bc85a48db6ae6/AndroidManifest.xml
Stripped manifest of artifact: AndroidManifest.xml (com.android.support:support-fragment:26.1.0) -> /Users/Jalen/.gradle/caches/transforms-1/files-1.1/support-fragment-26.1.0.aar/253cc53d4a251488811e7dbcfc1dc47f/AndroidManifest.xml
Stripped manifest of artifact: AndroidManifest.xml (com.android.support:support-core-utils:26.1.0) -> /Users/Jalen/.gradle/caches/transforms-1/files-1.1/support-core-utils-26.1.0.aar/4f69a32a8c5fb043aa27d7af82ec4868/AndroidManifest.xml
Stripped manifest of artifact: AndroidManifest.xml (com.android.support:support-core-ui:26.1.0) -> /Users/Jalen/.gradle/caches/transforms-1/files-1.1/support-core-ui-26.1.0.aar/ccfbd7824b34090f772a3d43550eaf2e/AndroidManifest.xml
Stripped manifest of artifact: AndroidManifest.xml (com.android.support:support-compat:26.1.0) -> /Users/Jalen/.gradle/caches/transforms-1/files-1.1/support-compat-26.1.0.aar/4ecf89bcb9354078b8cb814d9b0fe114/AndroidManifest.xml
Stripped manifest of artifact: AndroidManifest.xml (android.arch.lifecycle:runtime:1.0.0) -> /Users/Jalen/.gradle/caches/transforms-1/files-1.1/runtime-1.0.0.aar/dd09cdc3a7b811ff867b90866faac374/AndroidManifest.xml

> Task :app:processReleaseResources
 'AndroidManifest.xml'...
 'res/layout/activity_home.xml'...
 'resources.arsc'...

> Task :app:mergeReleaseShaders
###############################################################
> Task :app:transformClassesAndResourcesWithStripClassAndResForRelease
Stripped jar: /Users/Jalen/.gradle/caches/transforms-1/files-1.1/appcompat-v7-26.1.0.aar/48e73afb10bf45ecb81b09a5df79d77e/jars/classes.jar
Copied to jar: /Users/Jalen/WorkSpace/Andorid/YzTest/Plugin/app/build/intermediates/transforms/stripClassAndRes/release/0.jar
Stripped jar: /Users/Jalen/.gradle/caches/transforms-1/files-1.1/animated-vector-drawable-26.1.0.aar/412501fe842f9ebba87ce7b1c86441c8/jars/classes.jar
Stripped jar: /Users/Jalen/.gradle/caches/transforms-1/files-1.1/support-vector-drawable-26.1.0.aar/585d84399fccccaec48d46c4b3df3f0d/jars/classes.jar
Stripped jar: /Users/Jalen/.gradle/caches/transforms-1/files-1.1/support-v4-26.1.0.aar/8c93c1720634fb0dce81c96b2dc658a5/jars/classes.jar
Stripped jar: /Users/Jalen/.gradle/caches/transforms-1/files-1.1/support-media-compat-26.1.0.aar/248332f86284791f967bc85a48db6ae6/jars/classes.jar
Stripped jar: /Users/Jalen/.gradle/caches/transforms-1/files-1.1/support-fragment-26.1.0.aar/253cc53d4a251488811e7dbcfc1dc47f/jars/classes.jar
Stripped jar: /Users/Jalen/.gradle/caches/transforms-1/files-1.1/support-core-utils-26.1.0.aar/4f69a32a8c5fb043aa27d7af82ec4868/jars/classes.jar
Stripped jar: /Users/Jalen/.gradle/caches/transforms-1/files-1.1/support-core-ui-26.1.0.aar/ccfbd7824b34090f772a3d43550eaf2e/jars/classes.jar
Stripped jar: /Users/Jalen/.gradle/caches/transforms-1/files-1.1/support-compat-26.1.0.aar/4ecf89bcb9354078b8cb814d9b0fe114/jars/classes.jar
Stripped jar: /Users/Jalen/.gradle/caches/modules-2/files-2.1/com.android.support/support-annotations/26.1.0/814258103cf26a15fcc26ecce35f5b7d24b73f8/support-annotations-26.1.0.jar
Copied to jar: /Users/Jalen/WorkSpace/Andorid/YzTest/Plugin/app/build/intermediates/transforms/stripClassAndRes/release/1.jar
Stripped jar: /Users/Jalen/.gradle/caches/transforms-1/files-1.1/runtime-1.0.0.aar/dd09cdc3a7b811ff867b90866faac374/jars/classes.jar
Stripped jar: /Users/Jalen/.gradle/caches/modules-2/files-2.1/android.arch.lifecycle/common/1.0.0/e414a4cb28434e25c4f6aa71426eb20cf4874ae9/common-1.0.0.jar
Stripped jar: /Users/Jalen/.gradle/caches/modules-2/files-2.1/android.arch.core/common/1.0.0/a2d487452376193fc8c103dd2b9bd5f2b1b44563/common-1.0.0.jar
Copied to file: /Users/Jalen/WorkSpace/Andorid/YzTest/Plugin/app/build/intermediates/transforms/stripClassAndRes/release/2/android/support/constraint/R.class
Copied to file: /Users/Jalen/WorkSpace/Andorid/YzTest/Plugin/app/build/intermediates/transforms/stripClassAndRes/release/2/android/support/constraint/R$id.class
Copied to file: /Users/Jalen/WorkSpace/Andorid/YzTest/Plugin/app/build/intermediates/transforms/stripClassAndRes/release/2/android/support/constraint/R$styleable.class
Copied to file: /Users/Jalen/WorkSpace/Andorid/YzTest/Plugin/app/build/intermediates/transforms/stripClassAndRes/release/2/android/support/constraint/R$attr.class
Copied to file: /Users/Jalen/WorkSpace/Andorid/YzTest/Plugin/app/build/intermediates/transforms/stripClassAndRes/release/2/com/yangzhe/yztest/plugin/R.class
Copied to file: /Users/Jalen/WorkSpace/Andorid/YzTest/Plugin/app/build/intermediates/transforms/stripClassAndRes/release/2/com/yangzhe/yztest/plugin/R$bool.class
Copied to file: /Users/Jalen/WorkSpace/Andorid/YzTest/Plugin/app/build/intermediates/transforms/stripClassAndRes/release/2/com/yangzhe/yztest/plugin/R$id.class
Copied to file: /Users/Jalen/WorkSpace/Andorid/YzTest/Plugin/app/build/intermediates/transforms/stripClassAndRes/release/2/com/yangzhe/yztest/plugin/R$mipmap.class
Copied to file: /Users/Jalen/WorkSpace/Andorid/YzTest/Plugin/app/build/intermediates/transforms/stripClassAndRes/release/2/com/yangzhe/yztest/plugin/BuildConfig.class
Copied to file: /Users/Jalen/WorkSpace/Andorid/YzTest/Plugin/app/build/intermediates/transforms/stripClassAndRes/release/2/com/yangzhe/yztest/plugin/R$styleable.class
Copied to file: /Users/Jalen/WorkSpace/Andorid/YzTest/Plugin/app/build/intermediates/transforms/stripClassAndRes/release/2/com/yangzhe/yztest/plugin/R$style.class
Copied to file: /Users/Jalen/WorkSpace/Andorid/YzTest/Plugin/app/build/intermediates/transforms/stripClassAndRes/release/2/com/yangzhe/yztest/plugin/R$anim.class
Copied to file: /Users/Jalen/WorkSpace/Andorid/YzTest/Plugin/app/build/intermediates/transforms/stripClassAndRes/release/2/com/yangzhe/yztest/plugin/R$string.class
Copied to file: /Users/Jalen/WorkSpace/Andorid/YzTest/Plugin/app/build/intermediates/transforms/stripClassAndRes/release/2/com/yangzhe/yztest/plugin/R$color.class
Copied to file: /Users/Jalen/WorkSpace/Andorid/YzTest/Plugin/app/build/intermediates/transforms/stripClassAndRes/release/2/com/yangzhe/yztest/plugin/HomeActivity.class
Copied to file: /Users/Jalen/WorkSpace/Andorid/YzTest/Plugin/app/build/intermediates/transforms/stripClassAndRes/release/2/com/yangzhe/yztest/plugin/R$dimen.class
Copied to file: /Users/Jalen/WorkSpace/Andorid/YzTest/Plugin/app/build/intermediates/transforms/stripClassAndRes/release/2/com/yangzhe/yztest/plugin/R$integer.class
Copied to file: /Users/Jalen/WorkSpace/Andorid/YzTest/Plugin/app/build/intermediates/transforms/stripClassAndRes/release/2/com/yangzhe/yztest/plugin/R$layout.class
Copied to file: /Users/Jalen/WorkSpace/Andorid/YzTest/Plugin/app/build/intermediates/transforms/stripClassAndRes/release/2/com/yangzhe/yztest/plugin/R$attr.class
Copied to file: /Users/Jalen/WorkSpace/Andorid/YzTest/Plugin/app/build/intermediates/transforms/stripClassAndRes/release/2/com/yangzhe/yztest/plugin/R$drawable.class
Stripped jar: /Users/Jalen/WorkSpace/Andorid/YzTest/Plugin/app/build/intermediates/transforms/mergeJavaRes/release/0.jar

BUILD SUCCESSFUL in 5s
30 actionable tasks: 30 executed
[100%] /sdcard/Test.apk

```

### 错误日志

```
05-01 19:51:31.014 18386-18386/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.yangzhe.yztest, PID: 18386
                                                   java.lang.RuntimeException: Unable to start activity ComponentInfo{com.yangzhe.yztest/com.didi.virtualapk.core.A$1}: android.content.res.Resources$NotFoundException: Resource ID #0x9f020000
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2853)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2918)
                                                       at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1628)
                                                       at android.os.Handler.dispatchMessage(Handler.java:110)
                                                       at android.os.Looper.loop(Looper.java:203)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6406)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1113)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:974)
                                                    Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x9f020000
                                                       at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:204)
                                                       at android.content.res.Resources.loadXmlResourceParser(Resources.java:2940)
                                                       at android.content.res.Resources.getLayout(Resources.java:1291)
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:424)
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
                                                       at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287)
                                                       at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
                                                       at com.yangzhe.yztest.plugin.HomeActivity.onCreate(HomeActivity.java:11)
                                                       at android.app.Activity.performCreate(Activity.java:6758)
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1122)
                                                       at com.didi.virtualapk.internal.VAInstrumentation.callActivityOnCreate(VAInstrumentation.java:145)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2806)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2918) 
                                                       at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1628) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:110) 
                                                       at android.os.Looper.loop(Looper.java:203) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:6406) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1113) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:974) 
```

4. 复现步骤
（1） 运行 官方 demo成功，但是自己写一个例子出的问题
（2）编译插件和编译宿主都运行ok

# VirtualAPK 构建相关

1. gradle version
```
distributionUrl=https\://services.gradle.org/distributions/gradle-4.1-all.zip
```

2.  android gradle plugin version
```
  classpath 'com.android.tools.build:gradle:3.0.1'
```
3. VirtualAPK plugin version
```
 classpath 'com.didi.virtualapk:gradle:0.9.7'
```
4. OS type
```
mac  10.13.2
```

**Comment by superqiaopu** [comment]
packageId范围 0x03～0x7e

**Comment by StudyLifeTime** [comment]
packageId范围 0x03～0x7e ，我尝试过了，也没有解决问题，通过你们的指导，解决了问题。
发现我插件依赖了：
```
    implementation 'com.android.support.constraint:constraint-layout:1.1.0'
```
宿主没有依赖这个组件，导致找不到相应的资源文件

我只重新编译了 插件，然后发现还是不可以，最后宿主和插件都重新编译了，才正常运行
希望对别的同学有帮助，我这里详细描述一下我的问题
