### ISSUE TITLE
报错了。

### ISSUE THREAD

**Issue by moziqi** [didi/VirtualAPK#21]
` FATAL EXCEPTION: main
                                                                     Process: com.didi.virtualapk, PID: 12503
                                                                     java.lang.IllegalAccessError: Class ref in pre-verified class resolved to unexpected implementation
                                                                         at dalvik.system.DexFile.defineClassNative(Native Method)
                                                                         at dalvik.system.DexFile.defineClass(DexFile.java:222)
                                                                         at dalvik.system.DexFile.loadClassBinaryName(DexFile.java:215)
                                                                         at dalvik.system.DexPathList.findClass(DexPathList.java:322)
                                                                         at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:54)
                                                                         at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
                                                                         at java.lang.ClassLoader.loadClass(ClassLoader.java:491)
                                                                         at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
                                                                         at android.app.Instrumentation.newActivity(Instrumentation.java:1061)
                                                                         at com.didi.virtualapk.internal.VAInstrumentation.newActivity(VAInstrumentation.java:101)
                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2104)
                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2236)
                                                                         at android.app.ActivityThread.access$800(ActivityThread.java:138)
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1199)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                         at android.os.Looper.loop(Looper.java:136)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5095)
                                                                         at java.lang.reflect.Method.invokeNative(Native Method)
                                                                         at java.lang.reflect.Method.invoke(Method.java:515)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:602)
                                                                         at dalvik.system.NativeStart.main(Native Method)`

**Comment by wsf5918** [comment]
http://blog.csdn.net/berber78/article/details/41721877

**Comment by singwhatiwanna** [comment]
无效issue，关闭
