### ISSUE TITLE
小米6(Android8.0) 启动插件crash，似乎是兼容性错误

### ISSUE THREAD

**Issue by Luckflower** [didi/VirtualAPK#214]
hi，我下载了源码， 运行demo，出现如下崩溃信息，提示找不到abc_action_bar_home_description 这个res，其实这个res是源码下的，并且在最终的编译文件中是存在的，请问这是怎么回事呀，非常感谢
Process: com.didi.virtualapk, PID: 7434
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.didi.virtualapk/com.didi.virtualapk.core.A$1}: android.content.res.Resources$NotFoundException: Drawable com.didi.virtualapk:string/abc_action_bar_home_description with resource ID #0x7f0a0000
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2836)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2911)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1608)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6665)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)
     Caused by: android.content.res.Resources$NotFoundException: Drawable com.didi.virtualapk:string/abc_action_bar_home_description with resource ID #0x7f0a0000
     Caused by: android.content.res.Resources$NotFoundException: File 转到主屏幕 from drawable resource ID #0x7f0a0000
        at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:805)
        at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:619)
        at android.content.res.MiuiResourcesImpl.loadDrawable(MiuiResourcesImpl.java:305)
        at android.content.res.Resources.getDrawableForDensity(Resources.java:890)
        at android.content.res.Resources.getDrawable(Resources.java:832)
        at android.content.Context.getDrawable(Context.java:614)
        at com.android.internal.widget.ToolbarWidgetWrapper.setIcon(ToolbarWidgetWrapper.java:322)
        at com.android.internal.widget.ActionBarOverlayLayout.setIcon(ActionBarOverlayLayout.java:742)
        at com.android.internal.policy.PhoneWindow.setDefaultIcon(PhoneWindow.java:1755)
        at android.app.Activity.initWindowDecorActionBar(Activity.java:2699)
        at android.app.Activity.setContentView(Activity.java:2714)
        at com.didi.virtualapk.demo.MainActivity.onCreate(MainActivity.java:30)
        at android.app.Activity.performCreate(Activity.java:7057)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
        at com.didi.virtualapk.internal.VAInstrumentation.callActivityOnCreate(VAInstrumentation.java:222)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2789)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2911)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1608)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)

**Comment by helloing6** [comment]
不是兼容性问题，是没有找到资源的问题

**Comment by Luckflower** [comment]
问题解决了，非常感谢，

**Comment by Gundam0079** [comment]
请问如何解决的

**Comment by Luckflower** [comment]
权限没有打开，把权限都打开就ok了

**Comment by Gundam0079** [comment]
哪些权限呢可以粘贴一下么  宿主中的权限么

**Comment by sdgSnow** [comment]
我权限全部都手动给了，还是不行啊

**Comment by yifei8** [comment]
> 权限没有打开，把权限都打开就ok了

请问什么权限没打开，能给出具体的权限么和原因么。
