### ISSUE TITLE
插件访问 宿主 SDK 报出类找不到异常

### ISSUE THREAD

**Issue by 1022-zhang** [didi/VirtualAPK#223]
1.插件 工程与宿主工程依赖同一个 本地私服SDK，访问的类 有无参构造方法
2. 运行过程： 宿主打开插件页面后，在插件页面 访问 宿主 SDK 类
3. 结果：崩溃
4. 构建过程：宿主编译，gradlew clean assembleRelease；完成后 插件编译 gradlew clean assemblePlugin
5.VirtualAPK 配置com.didi.virtualapk:core:0.9.6-dev ，     classpath 'com.didi.virtualapk:gradle:0.9.8.4.4-dev'
6. Android 版本 5.0.2
看源码 ，访问类使用的是反射。访问不到的类 通过查看 依赖文件，确实存在

烦请大神能 解答一下

异常日志如下：
注：插件访问SDK 的目标类为**VirtualPluginAPK**

 16364-16364/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: cn.test.virtualapkdemo, PID: 16364
                                                   **java.lang.NoClassDefFoundError: Failed resolution of: Lcn/test/virtualapkhost/VirtualPluginAPK**;
                                                       at cn.test.virtualapkplugindemo.PluginMainActivity$1.onClick(Unknown Source)
                                                       at android.view.View.performClick(View.java:4832)
                                                       at android.view.View$PerformClick.run(View.java:19839)
                                                       at android.os.Handler.handleCallback(Handler.java:739)
                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                       at android.os.Looper.loop(Looper.java:211)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5335)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:372)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1016)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)
                                                    Caused by: java.lang.ClassNotFoundException: Didn't find class "cn.test.virtualapkhost.VirtualPluginAPK" on path: DexPathList[[zip file "/data/app/cn.test.virtualapkdemo-1/base.apk", zip file "/storage/emulated/0/Test1.apk"],nativeLibraryDirectories=[/data/app/cn.test.virtualapkdemo-1/lib/arm, /vendor/lib, /system/lib, /data/data/cn.test.virtualapkdemo/app_valibs]]
                                                       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                       at cn.test.virtualapkplugindemo.PluginMainActivity$1.onClick(Unknown Source) 
                                                       at android.view.View.performClick(View.java:4832) 
                                                       at android.view.View$PerformClick.run(View.java:19839) 
                                                       at android.os.Handler.handleCallback(Handler.java:739) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                       at android.os.Looper.loop(Looper.java:211) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5335) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at java.lang.reflect.Method.invoke(Method.java:372) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1016) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811) 
                                                   	Suppressed: java.lang.ClassNotFoundException: cn.test.virtualapkhost.VirtualPluginAPK
                                                       at java.lang.Class.classForName(Native Method)
                                                       at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                       at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                       		... 12 more
                                                    Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
 1259-1597/? E/InputDispatcher: channel '2a3451fb cn.test.virtualapkdemo/com.didi.virtualapk.core.A$1 (server)' ~ Channel is unrecoverably broken and will be disposed!

辛苦了

**Comment by 1022-zhang** [comment]
测试了三种情况：
1. 插件与宿主 依赖同一个远程SDK，类找不到异常。
2.插件工程依赖本地 SDK ，与 宿主 工程本地依赖 同一个，方法不存在异常
3.插件访问宿主未依赖的 SDK ，可正常访问

按 Wiki 写明的 插件与宿主 通信方案，上述情形理论上不应该出错。甚为不解
烦请 刚哥解惑一下

**Comment by 1022-zhang** [comment]
问题已经解决。发现是 clean 命令 失效，apk 未变更导致修改失效了。乌龙了
