### ISSUE TITLE
You need to use a Theme.AppCompat theme （尝试使用搜到该问题的其他issue的解决方案仍然无效）

### ISSUE THREAD

**Issue by Thereisnospon** [didi/VirtualAPK#229]
错误：
```
                    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.thereisnospon.gls/com.didi.virtualapk.core.A$1}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2911)
                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2989)
                                                                           at android.app.ActivityThread.-wrap11(Unknown Source:0)
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1688)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                           at android.os.Looper.loop(Looper.java:164)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:6753)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:482)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
                                                                        Caused by: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
                                                                           at android.support.v7.app.AppCompatDelegateImplV9.createSubDecor(AppCompatDelegateImplV9.java:354)
                                                                           at android.support.v7.app.AppCompatDelegateImplV9.ensureSubDecor(AppCompatDelegateImplV9.java:323)
                                                                           at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:284)
                                                                           at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
                                                                           at com.thereisnospon.base.activity.BaseActivity.onCreate(BaseActivity.java:37)
                                                                           at android.app.Activity.performCreate(Activity.java:7026)
                                                                           at android.app.Activity.performCreate(Activity.java:7017)
                                                                           at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1231)
                                                                           at com.didi.virtualapk.internal.VAInstrumentation.callActivityOnCreate(VAInstrumentation.java:141)
                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2864)
                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2989) 
                                                                           at android.app.ActivityThread.-wrap11(Unknown Source:0) 
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1688) 
                                                                           at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                           at android.os.Looper.loop(Looper.java:164) 
                                                                           at android.app.ActivityThread.main(ActivityThread.java:6753) 
                                                                           at java.lang.reflect.Method.invoke(Native Method) 
                                                                           at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:482) 
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 

```

环境：

classpath 'com.android.tools.build:gradle:3.0.0'
classpath  'com.didi.virtualapk:gradle:0.9.8.3'

宿主:

compile  'com.didi.virtualapk:core:0.9.0'
 compileSdkVersion 26
com.android.support:appcompat-v7:26.0.0

插件: 

compile  'com.didi.virtualapk:core:0.9.0'
compileSdkVersion 26
com.android.support:appcompat-v7:26.0.0

```
virtualApk {
    // 插件资源表中的packageId，需要确保不同插件有不同的packageId.
    packageId = 0x6f

    // 宿主工程application模块的路径，插件的构建需要依赖这个路径,我这个宿主工程和插件工程在同一级目录下,所以下面这样写
    targetHost = '../app'

    //默认为true，如果插件有引用宿主的类，那么这个选项可以使得插件和宿主保持混淆一致
    applyHostMapping = true
}
```
插件定义的activity,manifest.xml

```
    <application>
        <activity android:name=".PlgActivity" android:theme="@style/Theme.AppCompat.Light.DarkActionBar"/>
    </application>
```
步骤。

1. build host 的 debug apk
2. assmblePlugin 执行插件的打包。

机型 android 8.1.0

**Comment by yangchaoxun** [comment]
这个问题解决了吗

**Comment by Thereisnospon** [comment]
@yangchaoxun  解决了。  我是自定义了一个 task 依赖 assmblePlugin ，然后命令行指定自定义的 task ，但是这个打包是通过读取 gradle 启动参数 进行的， 必须得要在命令行指定 assmblePlugin。。。

**Comment by sky008yyh** [comment]
@Thereisnospon 大神，你这个怎么解决的，能不能给个DEMO代码看看?

**Comment by superqiaopu** [comment]
@Thereisnospon 新版已解决这个问题。

**Comment by superqiaopu** [comment]
@Thereisnospon 因为要在 Evaluate 阶段前初始化一些东西，所以需要通过读取启动参数来判断是否执行初始化逻辑，如果有更好的方法欢迎交流。

**Comment by sdgSnow** [comment]
我是添加透明activity的时候出现这个问题的，请问下有人解决了吗
