### ISSUE TITLE
Android 8.0资源找不到

### ISSUE THREAD

**Issue by q594989927** [didi/VirtualAPK#234]
插件使用场景：
宿主加载插件后，插件注册到宿主页面跳转路由，宿主通过路由跳转插件页面，插件依赖宿主fragment基类，宿主fragment基类加载插件资源。
debug运行，宿主和插件不混淆条件下，宿主正常跳转插件
release运行，宿主和插件都混淆，宿主无法正常跳转插件，crash报找不到资源android.content.res.Resources$NotFoundException: Resource ID #0x71020001
debug运行，宿主和插件都混淆，宿主无法正常跳转插件，crash报找不到资源android.content.res.Resources$NotFoundException: Resource ID #0x71020001
release运行，宿主和插件不混淆条件下，宿主正常跳转插件，crash报找不到资源
运行环境：华为荣耀V8 android 8.0, 低版本手机运行未发现问题
附: 
 # CRASH STACK: 
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.yoogor.demo/com.yoogor.demo.base.app.FragmentContainerActivity}: android.content.res.Resources$NotFoundException: Resource ID #0x71020001
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3194)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3302)
        at android.app.ActivityThread.-wrap12(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1891)
        at android.os.Handler.dispatchMessage(Handler.java:108)
        at android.os.Looper.loop(Looper.java:166)
        at android.app.ActivityThread.main(ActivityThread.java:7425)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
     Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x71020001
        at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:279)
        at android.content.res.Resources.loadXmlResourceParser(Resources.java:2310)
        at android.content.res.Resources.getLayout(Resources.java:1293)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:421)
        at com.yoogor.demo.base.app.a.onCreateView(AbsFragment.java:104)
        at android.app.Fragment.performCreateView(Fragment.java:2626)
        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1279)
        at android.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1554)
        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1617)
        at android.app.FragmentManagerImpl.dispatchMoveToState(FragmentManager.java:3043)
        at android.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:2999)
        at android.app.FragmentController.dispatchActivityCreated(FragmentController.java:178)
        at android.app.Activity.performCreateCommon(Activity.java:7365)
        at android.app.Activity.performCreate(Activity.java:7375)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1218)
        at com.didi.virtualapk.internal.VAInstrumentation.callActivityOnCreate(VAInstrumentation.java:223)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3147)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3302) 
        at android.app.ActivityThread.-wrap12(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1891) 
        at android.os.Handler.dispatchMessage(Handler.java:108) 
        at android.os.Looper.loop(Looper.java:166) 
        at android.app.ActivityThread.main(ActivityThread.java:7425) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921) 
    #++++++++++++++++++++++++++++++++++++++++++#
插件打包命令:assemblePlugin
插件已配置 
virtualApk {
    packageId = 0x71 // the package id of Resources.
    targetHost = "$rootDir/app" // the path of application module in host project.
    applyHostMapping = true //optional, default value: true.
}
插件与宿主lib依赖相同
compile 'com.didi.virtualapk:core:0.9.6'
gradle 插件版本
classpath 'com.android.tools.build:gradle:3.0.1'
classpath 'com.didi.virtualapk:gradle:0.9.8.4'
开发环境 Win10 AS 3.1.2

**Comment by superqiaopu** [comment]
加qq群交流：656602897

**Comment by Dovar66** [comment]
资源被shrink掉了吧

**Comment by oywjAndroid** [comment]
有解决吗？我也遇到同样的问题。
