### ISSUE TITLE
开启混淆后，混淆冲突

### ISSUE THREAD

**Issue by ryan-yuan** [didi/VirtualAPK#244]
Warning: xxx.manager.DownloadManager: method 'void restartDownload(long[])' can't be mapped to 'a' because it would conflict with method 'getWhereArgsForIds', which is already being mapped to 'a'
导致
Caused by: java.io.IOException: Please correct the above warnings first.
	at proguard.obfuscate.Obfuscator.execute(Obfuscator.java:411)
	at proguard.ProGuard.obfuscate(ProGuard.java:355)
	at proguard.ProGuard.execute(ProGuard.java:152)
	at com.android.build.gradle.internal.transforms.BaseProguardAction.runProguard(BaseProguardAction.java:61)
	at com.android.build.gradle.internal.transforms.ProGuardTransform.doMinification(ProGuardTransform.java:253)
	at com.android.build.gradle.internal.transforms.ProGuardTransform.access$000(ProGuardTransform.java:63)
	at com.android.build.gradle.internal.transforms.ProGuardTransform$1.run(ProGuardTransform.java:173)
	at com.android.builder.tasks.Job.runTask(Job.java:47)
	at com.android.build.gradle.tasks.SimpleWorkQueue$EmptyThreadContext.runTask(SimpleWorkQueue.java:41)
	at com.android.builder.tasks.WorkQueue.run(WorkQueue.java:259)

**Comment by superqiaopu** [comment]
请先查看相关Wiki：
 [Demo 工程运行须知](https://github.com/didi/VirtualAPK/wiki/Demo-%E5%B7%A5%E7%A8%8B%E8%BF%90%E8%A1%8C%E9%A1%BB%E7%9F%A5)
[提问必看](https://github.com/didi/VirtualAPK/wiki/%E6%8F%90%E9%97%AE%E5%BF%85%E7%9C%8B)
[常见问题解答(不定时更新)](https://github.com/didi/VirtualAPK/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98%E8%A7%A3%E7%AD%94)
