### ISSUE TITLE
插件中接入了腾讯云直播，插件单独运行成功，生成插件也成功了，宿主启动插件播放 失败！

### ISSUE THREAD

**Issue by Jack1995** [didi/VirtualAPK#246]
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.fbi.rainbowpavilion, PID: 11339
                  java.lang.UnsatisfiedLinkError: No implementation found for void com.tencent.liteav.basic.log.TXCLog.nativeLogInit() (tried Java_com_tencent_liteav_basic_log_TXCLog_nativeLogInit and Java_com_tencent_liteav_basic_log_TXCLog_nativeLogInit__)
                      at com.tencent.liteav.basic.log.TXCLog.nativeLogInit(Native Method)
                      at com.tencent.liteav.basic.log.TXCLog.init(TXCLog.java:31)
                      at com.tencent.rtmp.TXLivePlayer.<init>(TXLivePlayer.java:74)
                      at com.fbi.rainbowpavilion.module.game.GameRoomActivity.onCreate(GameRoomActivity.kt:23)
                      at android.app.Activity.performCreate(Activity.java:7003)
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1230)
                      at com.didi.virtualapk.internal.VAInstrumentation.callActivityOnCreate(VAInstrumentation.java:223)
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2899)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3046)
                      at android.app.ActivityThread.-wrap11(Unknown Source:0)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1688)
                      at android.os.Handler.dispatchMessage(Handler.java:105)
                      at android.os.Looper.loop(Looper.java:164)
                      at android.app.ActivityThread.main(ActivityThread.java:6798)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

找不到方法

**Comment by superqiaopu** [comment]
请先查看相关Wiki：
 [Demo 工程运行须知](https://github.com/didi/VirtualAPK/wiki/Demo-%E5%B7%A5%E7%A8%8B%E8%BF%90%E8%A1%8C%E9%A1%BB%E7%9F%A5)
[提问必看](https://github.com/didi/VirtualAPK/wiki/%E6%8F%90%E9%97%AE%E5%BF%85%E7%9C%8B)
[常见问题解答(不定时更新)](https://github.com/didi/VirtualAPK/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98%E8%A7%A3%E7%AD%94)
