### ISSUE TITLE
构建插件时报错Failed to notify project evaluation listener com/android/builder/dependency/ManifestDependency

### ISSUE THREAD

**Issue by VincentLoveAndroid** [didi/VirtualAPK#25]
插件宿主路径配置正确，
构建插件时候使用图形界面：assemblePlugin命令，报错如下：

Error:A problem occurred configuring project ':app'.
> Failed to notify project evaluation listener.
   > com/android/builder/dependency/ManifestDependency

**Comment by singwhatiwanna** [comment]
插件的构建请参考：[Demo 工程运行须知](https://github.com/didi/VirtualAPK/wiki/Demo-%E5%B7%A5%E7%A8%8B%E8%BF%90%E8%A1%8C%E9%A1%BB%E7%9F%A5)

**Comment by singwhatiwanna** [comment]
@VincentLoveAndroid 主要是由于Gradle以及buildTools的版本所导致的问题，请按照建议版本来。

**Comment by VincentLoveAndroid** [comment]
@singwhatiwanna 你好，按照demo配置了gradle 以及 buildTools版本，插件执行：
 gradle clean assemblePlugin
编译的时候仍旧报错：
Caused by: java.lang.ClassCastException: org.gradle.api.internal.tasks.DefaultTaskInputs$TaskInputUnionFileCollection cannot be cast to org.gradle.api.internal.file.collections.DefaultConfigurableFileCollection
或：
* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:processReleaseResources'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:66)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:66)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:25)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:110)
        at org.gradle.execution.SelectedTaskExecutionAction.execute(S

**Comment by VincentLoveAndroid** [comment]
@singwhatiwanna 
Caused by: java.lang.NullPointerException: Cannot invoke method getAt() on null object
        at com.didi.virtualapk.aapt.ArscEditor.slice(ArscEditor.groovy:61)
        at com.didi.virtualapk.aapt.ArscEditor$slice.call(Unknown Source)
        at com.didi.virtualapk.aapt.Aapt.filterPackage(Aapt.groovy:51)
        at com.didi.virtualapk.aapt.Aapt$filterPackage$0.call(Unknown Source)
        at com.didi.virtualapk.merge.ResourceMerger$_merge_closure2.doCall(ResourceMerger.groovy:73)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:590)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:571)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
        ... 68 more

**Comment by TheBloodElf** [comment]
我也遇到你这个错误，改了tool版本之后出现了下面的错误：
* What went wrong:
Execution failed for task ':app:processReleaseResources'.
> Cannot invoke method getAt() on null object

**Comment by qq634421026** [comment]
和你一样遇到这样的错误
* What went wrong:
Execution failed for task ':app:processReleaseResources'.
> Cannot invoke method getAt() on null object

**Comment by VincentLoveAndroid** [comment]
@qq634421026 @TheBloodElf @singwhatiwanna 对于Cannot invoke method getAt() on null object 这个问题最终发现要在插件app build.gradle加上：compile 'com.didi.virtualapk:core:0.9.0'依赖 文档没写😓，org.gradle.api.internal.tasks.DefaultTaskInputs$TaskInputUnionFileCollection cannot be cast to org.gradle.api.internal.file.collections.DefaultConfigurableFileCollection 这个问题则应该是本地gradle版本和使用的不一致造成

**Comment by qq634421026** [comment]
@VincentLoveAndroid  你好我在插件中增加了 compile 'com.didi.virtualapk:core:0.9.0'但是构建的时候还是会出现
Execution failed for task ':app:processReleaseResources'.
> Cannot invoke method getAt() on null object

的错误

**Comment by qq634421026** [comment]
增加 compile 'com.didi.virtualapk:core:0.9.0'之后执行./gradlew clean assemblePlugin还是报Cannot invoke method getAt() on null object错

**Comment by TheBloodElf** [comment]
@singwhatiwanna 希望尽快解决这个问题，因为很想接入此库

**Comment by danieldaydan** [comment]
AS 版本2.3.2  
按照Demo配置gradle 以及 buildTools版本 编译报Caused by: java.lang.ClassCastException: org.gradle.api.internal.tasks.DefaultTaskInputs$TaskInputUnionFileCollection cannot be cast to org.gradle.api.internal.file.collections.DefaultConfigurableFileCollection

 buildTools版本改成与AS版本对应的就报Failed to notify project evaluation listener.
com/android/builder/dependency/ManifestDependency

**Comment by houliang** [comment]
出现
What went wrong:
Execution failed for task ':app:processReleaseResources'.
这个问题，module的依赖加上
compile 'com.android.support:appcompat-v7:找个版本'
依赖库以后没问题了

**Comment by haojunmin** [comment]
我的qq1149598411，我也遇到Execution failed for task ':app:processReleaseResources'.
Cannot invoke method getAt() on null object这个问题了，谁知道该怎么办？

**Comment by slksir** [comment]
好像还没人来解决这个问题啊。

**Comment by slksir** [comment]
估计滴滴自己写的那个gradle插件版本的问题。只能希望他们开发人员将版本升上去了。

**Comment by slksir** [comment]
Caused by: java.lang.NoClassDefFoundError: com/android/builder/dependency/ManifestDependency
        at com.didi.virtualapk.VAPlugin$_apply_closure1$_closure16.doCall(VAPlugin.groovy:72)
        at com.didi.virtualapk.VAPlugin$_apply_closure1.doCall(VAPlugin.groovy:52)
        at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:40)
        at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:25)
        at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:44)
        ... 61 more

**Comment by slksir** [comment]
@singwhatiwanna Gradle以及buildTools 版本你们有升级计划吗？真心希望你们能升级上去。现在开发的一般都是用的新版本

**Comment by singwhatiwanna** [comment]
@slksir 正在支持中，这个工作比较复杂，需要一些时间。

**Comment by zhulg** [comment]
不降到2.14.1是不行的，降后解决。
