### ISSUE TITLE
加载插件时报错java.lang.ClassNotFoundException:

### ISSUE THREAD

**Issue by 396767441** [didi/VirtualAPK#260]
core version : 'com.didi.virtualapk:core:0.9.6'
问题机型，系统版本:OPPO-R15、android:8.1.0
复现步骤：宿主加载插件时报错
完整log
09-05 16:11:03.465 27197-27197/com.oppo.autotoolplatform.host D/DataBinderMapperProxy: Try to find the class: android.databinding.DataBinderMapper_com_oppo_autotoolplatform_plugin
09-05 16:11:03.469 27197-27197/com.oppo.autotoolplatform.host W/DataBinderMapperProxy: java.lang.ClassNotFoundException: android.databinding.DataBinderMapper_com_oppo_autotoolplatform_plugin
                                                                                           at java.lang.Class.classForName(Native Method)
                                                                                           at java.lang.Class.forName(Class.java:453)
                                                                                           at android.databinding.DataBinderMapperProxy.onAddedLoadedPlugin(DataBinderMapperProxy.java:93)
                                                                                           at com.didi.virtualapk.PluginManager.loadPlugin(PluginManager.java:241)
                                                                                           at com.oppo.autotoolplatform.host.MainActivity.onCreate(MainActivity.java:36)
                                                                                           at android.app.Activity.performCreate(Activity.java:7301)
                                                                                           at android.app.Activity.performCreate(Activity.java:7292)
                                                                                           at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1215)
                                                                                           at com.didi.virtualapk.internal.VAInstrumentation.callActivityOnCreate(VAInstrumentation.java:223)
                                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2928)
                                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3053)
                                                                                           at android.app.ActivityThread.-wrap11(Unknown Source:0)
                                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1772)
                                                                                           at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                           at android.os.Looper.loop(Looper.java:197)
                                                                                           at android.app.ActivityThread.main(ActivityThread.java:7022)
                                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                                           at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:514)
                                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:837)
                                                                                        Caused by: java.lang.ClassNotFoundException: Didn't find class "android.databinding.DataBinderMapper_com_oppo_autotoolplatform_plugin" on path: DexPathList[[zip file "/data/user/0/com.oppo.autotoolplatform.host/files/Test.apk"],nativeLibraryDirectories=[/data/user/0/com.oppo.autotoolplatform.host/app_valibs, /system/lib64, /vendor/lib64]]
                                                                                           at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
                                                                                           at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
                                                                                           at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                                           at java.lang.Class.classForName(Native Method) 
                                                                                           at java.lang.Class.forName(Class.java:453) 
                                                                                           at android.databinding.DataBinderMapperProxy.onAddedLoadedPlugin(DataBinderMapperProxy.java:93) 
                                                                                           at com.didi.virtualapk.PluginManager.loadPlugin(PluginManager.java:241) 
                                                                                           at com.oppo.autotoolplatform.host.MainActivity.onCreate(MainActivity.java:36) 
                                                                                           at android.app.Activity.performCreate(Activity.java:7301) 
                                                                                           at android.app.Activity.performCreate(Activity.java:7292) 
                                                                                           at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1215) 
                                                                                           at com.didi.virtualapk.internal.VAInstrumentation.callActivityOnCreate(VAInstrumentation.java:223) 
                                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2928) 
                                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3053) 
                                                                                           at android.app.ActivityThread.-wrap11(Unknown Source:0) 
                                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1772) 
                                                                                           at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                           at android.os.Looper.loop(Looper.java:197) 
                                                                                           at android.app.ActivityThread.main(ActivityThread.java:7022) 
                                                                                           at java.lang.reflect.Method.invoke(Native Method) 
                                                                                           at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:514) 
                                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:837)

**Comment by 396767441** [comment]
构建失败后跳转到插件崩溃找不到类
