### ISSUE TITLE
无法加载apk中的so库？

### ISSUE THREAD

**Issue by chaooooooo** [didi/VirtualAPK#266]
10-01 17:28:43.007 10719 10719 D AndroidRuntime: Shutting down VM
10-01 17:28:43.008 10719 10719 E AndroidRuntime: FATAL EXCEPTION: main
10-01 17:28:43.008 10719 10719 E AndroidRuntime: Process: chao.app.gamecenter, PID: 10719
10-01 17:28:43.008 10719 10719 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{chao.app.gamecenter/com.didi.virtualapk.core.D$1}: java.lang.IllegalArgumentException: Unable to find native library main using classloader: dalvik.system.DexClassLoader[DexPathList[[zip file "/storage/emulated/0/Android/data/chao.app.gamecenter/cache/nes2.apk"],nativeLibraryDirectories=[/data/user/0/chao.app.gamecenter/app_valibs, /system/lib, /vendor/lib]]]
10-01 17:28:43.008 10719 10719 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2665)
10-01 17:28:43.008 10719 10719 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
10-01 17:28:43.008 10719 10719 E AndroidRuntime: 	at android.app.ActivityThread.-wrap12(ActivityThread.java)
10-01 17:28:43.008 10719 10719 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
10-01 17:28:43.008 10719 10719 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
10-01 17:28:43.008 10719 10719 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
10-01 17:28:43.008 10719 10719 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6119)
10-01 17:28:43.008 10719 10719 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-01 17:28:43.008 10719 10719 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
10-01 17:28:43.008 10719 10719 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
10-01 17:28:43.008 10719 10719 E AndroidRuntime: Caused by: java.lang.IllegalArgumentException: Unable to find native library main using classloader: dalvik.system.DexClassLoader[DexPathList[[zip file "/storage/emulated/0/Android/data/chao.app.gamecenter/cache/nes2.apk"],nativeLibraryDirectories=[/data/user/0/chao.app.gamecenter/app_valibs, /system/lib, /vendor/lib]]]
10-01 17:28:43.008 10719 10719 E AndroidRuntime: 	at android.app.NativeActivity.onCreate(NativeActivity.java:168)
10-01 17:28:43.008 10719 10719 E AndroidRuntime: 	at com.imagine.BaseActivity.onCreate(Unknown Source)
10-01 17:28:43.008 10719 10719 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:6679)
10-01 17:28:43.008 10719 10719 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
10-01 17:28:43.008 10719 10719 E AndroidRuntime: 	at com.didi.virtualapk.internal.VAInstrumentation.callActivityOnCreate(VAInstrumentation.java:156)
10-01 17:28:43.008 10719 10719 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
10-01 17:28:43.008 10719 10719 E AndroidRuntime: 	... 9 more
10-01 17:28:43.020  1710  3516 W ActivityManager:   Force finishing activity chao.app.gamecenter/com.didi.virtualapk.core.D$1

**Comment by chaooooooo** [comment]
resolved
