### ISSUE TITLE
把PluginDemo中Manifest的activity和service的注册注释后打开插件发生crash

### ISSUE THREAD

**Issue by just1296** [didi/VirtualAPK#27]
FATAL EXCEPTION: main
                                                                   Process: com.didi.virtualapk, PID: 9606
                                                                   java.lang.IllegalStateException: Could not execute method for android:onClick
                                                                       at android.view.View$DeclaredOnClickListener.onClick(View.java:4458)
                                                                       at android.view.View.performClick(View.java:5204)
                                                                       at android.view.View$PerformClick.run(View.java:21153)
                                                                       at android.os.Handler.handleCallback(Handler.java:739)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                       at android.os.Looper.loop(Looper.java:148)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                    Caused by: java.lang.reflect.InvocationTargetException
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at android.view.View$DeclaredOnClickListener.onClick(View.java:4453)
                                                                       at android.view.View.performClick(View.java:5204) 
                                                                       at android.view.View$PerformClick.run(View.java:21153) 
                                                                       at android.os.Handler.handleCallback(Handler.java:739) 
                                                                       at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                       at android.os.Looper.loop(Looper.java:148) 
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
                                                                    Caused by: java.lang.RuntimeException: can not find ComponentInfo{com.didi.virtualapk.demo/com.didi.virtualapk.demo.aidl.BookManagerActivity}
                                                                       at com.didi.virtualapk.internal.a.c(ComponentsHandler.java:94)
                                                                       at com.didi.virtualapk.internal.a.b(ComponentsHandler.java:84)
                                                                       at com.didi.virtualapk.internal.VAInstrumentation.execStartActivity(VAInstrumentation.java:63)
                                                                       at android.app.Activity.startActivityForResult(Activity.java:3930)
                                                                       at android.app.Activity.startActivityForResult(Activity.java:3890)
                                                                       at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:820)
                                                                       at android.app.Activity.startActivity(Activity.java:4213)
                                                                       at android.app.Activity.startActivity(Activity.java:4181)
                                                                       at com.didi.virtualapk.MainActivity.onButtonClick(MainActivity.java:53)

**Comment by singwhatiwanna** [comment]
@just1296 这个不能注释掉。四大组件不需要在宿主manifest中注册，但是插件manifest肯定需要注册啊，不然并不知道一个插件有哪些组件。
