### ISSUE TITLE
VirtualAPK在android5.0以下手机加载插件抛出异常

### ISSUE THREAD

**Issue by syc2018** [didi/VirtualAPK#273]
10-17 19:36:12.503 20005-20005/com.didi.virtualapk W/System.err: com.didi.virtualapk.utils.Reflector$ReflectedException: Oops!
        at com.didi.virtualapk.utils.Reflector.field(Reflector.java:130)
        at com.didi.virtualapk.internal.ResourcesManager$VivoResourcesCompat.createResources(ResourcesManager.java:251)
        at com.didi.virtualapk.internal.ResourcesManager$VivoResourcesCompat.access$100(ResourcesManager.java:245)
        at com.didi.virtualapk.internal.ResourcesManager.createResourcesSimple(ResourcesManager.java:94)
        at com.didi.virtualapk.internal.ResourcesManager.createResources(ResourcesManager.java:59)
        at com.didi.virtualapk.internal.LoadedPlugin.createResources(LoadedPlugin.java:104)
        at com.didi.virtualapk.internal.LoadedPlugin.<init>(LoadedPlugin.java:181)
        at com.didi.virtualapk.PluginManager.createLoadedPlugin(PluginManager.java:177)
        at com.didi.virtualapk.PluginManager.loadPlugin(PluginManager.java:318)
        at com.didi.virtualapk.MainActivity.loadPlugin(MainActivity.java:138)
        at com.didi.virtualapk.MainActivity.onCreate(MainActivity.java:53)
        at android.app.Activity.performCreate(Activity.java:5362)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1089)
        at com.didi.virtualapk.internal.VAInstrumentation.callActivityOnCreate(VAInstrumentation.java:156)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2160)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245)
        at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:3747)
        at android.app.ActivityThread.access$900(ActivityThread.java:140)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1208)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5143)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:602)
        at dalvik.system.NativeStart.main(Native Method)
    Caused by: java.lang.NoSuchFieldException: mThemeValues
        at java.lang.Class.getField(Class.java:724)
        at com.didi.virtualapk.utils.Reflector.findField(Reflector.java:136)
        at com.didi.virtualapk.utils.Reflector.field(Reflector.java:124)
    	... 26 more

**Comment by pjcchinaren** [comment]
请问怎么解决的
