### ISSUE TITLE
打开直接报错

### ISSUE THREAD

**Issue by noway211** [didi/VirtualAPK#28]
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.didi.virtualapk/com.didi.virtualapk.core.A$1}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2451)
                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2511)
                                                                         at android.app.ActivityThread.access$900(ActivityThread.java:165)
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1375)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                         at android.os.Looper.loop(Looper.java:150)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5621)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)

对theme的样式不支持

**Comment by zk0301** [comment]
issue里有人提到过啊。book那个改成继承activity即可。
也可以把host跳转那个，改成跳到main。

**Comment by chenenyu** [comment]
@noway211 你的插件apk是怎么生成的？ `assemblePlugin`?

**Comment by zk0301** [comment]
我没有用命令行。 我是用studio导入新建的项目，编译运行，然后卸载掉。然后apk push到sdcard下面。

**Comment by chenenyu** [comment]
@zk0301 这样是不行的，参考wiki中的demo指南，插件的编译需要执行特定的任务。

**Comment by zk0301** [comment]
@chenenyu 我确实成功了呀。= =！

**Comment by TheBloodElf** [comment]
@chenenyu 你那样属于独立模式没有问题，耦合模式需要把插件工程放入宿主工程目录中进行编译

**Comment by zk0301** [comment]
@TheBloodElf   问题是，我自己新创建了2个项目，一个host一个plug，重头开始做，按步骤来的，点击host按钮跳转报错，奇怪。targetHost应该怎么填。

**Comment by TheBloodElf** [comment]
@zk0301 我成功过一次，然后后面就失败了。。targetHost一般是相对路径，直接把插件工程复制进宿主工程根目录，然后targetHost写'../../VirtualAPK/app'，VirtualAPK是你宿主工程的名字

**Comment by singwhatiwanna** [comment]
@zk0301 @TheBloodElf 插件工程不是非得在宿主工程目录下面，你放在哪里都可以，只要targetHost指向宿主工程的Application module即可，大家别误解了。

**Comment by singwhatiwanna** [comment]
@noway211 @TheBloodElf 另外，这个错误是因为插件包构建不正确导致的，大家不要去改Activity的父类，它的父类就是AppCompatActivity。

如果你直接把插件工程run出来一个包，这个包肯定不是合法的插件包，看一下wiki，再有类似问题就直接关闭了。

**Comment by sdgSnow** [comment]
我是跳转到new的插件工程就可以，但是自己项目就不行了
