### ISSUE TITLE
框架在 API 19 的兼容上有些许问题

### ISSUE THREAD

**Issue by CD3108** [didi/VirtualAPK#282]
API 19  SM-P600 API 21 以上正常.

配置:
com.didi.virtualapk:core:0.9.8
classpath 'com.didi.virtualapk:gradle:0.9.8.6

PackageParserCompat 的
return PackageParserLegacy.parsePackage(context, apk, flags); 方法中
PackageParser.Package pkg = parser.parsePackage(apk, apk.getAbsolutePath(), context.getResources().getDisplayMetrics(), flags);
这句,pkg=null.与预期不一致,导致报错.

 FATAL EXCEPTION: main
                                                               Process: com.yonyou.ai, PID: 10224
                                                               java.lang.RuntimeException: error
                                                                   at com.didi.virtualapk.internal.utils.PackageParserCompat.parsePackage(PackageParserCompat.java:46)
                                                                   at com.didi.virtualapk.internal.LoadedPlugin.<init>(LoadedPlugin.java:152)
                                                                   at com.didi.virtualapk.PluginManager.createLoadedPlugin(PluginManager.java:177)
                                                                   at com.didi.virtualapk.PluginManager.loadPlugin(PluginManager.java:318)

**Comment by darrenjh** [comment]
mark

**Comment by darrenjh** [comment]
W/System.err: java.lang.RuntimeException: error
        at com.didi.virtualapk.internal.utils.PackageParserCompat.parsePackage(PackageParserCompat.java:46)
        at com.didi.virtualapk.internal.LoadedPlugin.<init>(LoadedPlugin.java:152)
        at com.didi.virtualapk.PluginManager.createLoadedPlugin(PluginManager.java:177)
        at com.didi.virtualapk.PluginManager.loadPlugin(PluginManager.java:318)
        at com.yang.hostapp.MainActivity$2.run(MainActivity.java:99)
        at java.lang.Thread.run(Thread.java:818)
