### ISSUE TITLE
Exception: multiple class loaders

### ISSUE THREAD

**Issue by zhangjizxc** [didi/VirtualAPK#288]
2019-01-03 14:12:20.177 19324-19324/com.didi.virtualapk E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.didi.virtualapk, PID: 19324
    java.lang.InternalError: Attempt to register dex file /storage/emulated/0/Test.apk!classes6.dex with multiple class loaders
        at dalvik.system.DexFile.defineClassNative(Native Method)
        at dalvik.system.DexFile.defineClass(DexFile.java:282)
        at dalvik.system.DexFile.loadClassBinaryName(DexFile.java:275)
        at dalvik.system.DexPathList$Element.findClass(DexPathList.java:677)
        at dalvik.system.DexPathList.findClass(DexPathList.java:466)
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:123)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.didi.virtualapk.internal.LoadedPlugin.<init>(LoadedPlugin.java:228)
        at com.didi.virtualapk.PluginManager.createLoadedPlugin(PluginManager.java:177)
        at com.didi.virtualapk.PluginManager.loadPlugin(PluginManager.java:318)
        at com.didi.virtualapk.MainActivity.loadPlugin(MainActivity.java:138)
        at com.didi.virtualapk.MainActivity.onCreate(MainActivity.java:53)
        at android.app.Activity.performCreate(Activity.java:7315)
        at android.app.Activity.performCreate(Activity.java:7306)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1215)
        at com.didi.virtualapk.internal.VAInstrumentation.callActivityOnCreate(VAInstrumentation.java:156)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2933)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3102)
        at android.app.ActivityThread.-wrap12(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1756)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6893)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:820)

**Comment by zhangjizxc** [comment]
请参考tinker的解决方案。https://github.com/Tencent/tinker/blob/master/tinker-android/tinker-android-loader/src/main/java/com/tencent/tinker/loader/AndroidNClassLoader.java

**Comment by zy14248** [comment]
Anynoe know how to solve this problem ?
