### ISSUE TITLE
databinding 不支持吗？

### ISSUE THREAD

**Issue by tonygshliu** [didi/VirtualAPK#292]
环境：
classpath 'com.android.tools.build:gradle:3.1.2'
classpath 'com.didi.virtualapk:gradle:0.9.8.6' 
 api 'com.didi.virtualapk:core:0.9.8'

com.didi.virtualapk.utils.Reflector$ReflectedException: Oops!
                                                                 at com.didi.virtualapk.utils.Reflector.constructor(Reflector.java:77)
                                                                 at com.didi.virtualapk.PluginManager.hookDataBindingUtil(PluginManager.java:185)
                                                                 at com.didi.virtualapk.PluginManager.hookCurrentProcess(PluginManager.java:145)
                                                                 at com.didi.virtualapk.PluginManager.<init>(PluginManager.java:139)
                                                                 at com.didi.virtualapk.PluginManager.createInstance(PluginManager.java:100)
                                                                 at com.didi.virtualapk.PluginManager.getInstance(PluginManager.java:85)
                                                                 at com.pa.zn.base.ZNApplication.initPluginLoader(ZNApplication.java:75)
                                                                 at com.pa.zn.base.ZNApplication.attachBaseContext(ZNApplication.java:55)
                                                                 at android.app.Application.attach(Application.java:224)
                                                                 at android.app.Instrumentation.newApplication(Instrumentation.java:1128)
                                                                 at android.app.LoadedApk.makeApplication(LoadedApk.java:1156)
                                                                 at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6529)
                                                                 at android.app.ActivityThread.access$1900(ActivityThread.java:267)
                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1963)
                                                                 at android.os.Handler.dispatchMessage(Handler.java:109)
                                                                 at android.os.Looper.loop(Looper.java:207)
                                                                 at android.app.ActivityThread.main(ActivityThread.java:7470)
                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)
                                                              Caused by: java.lang.NoSuchMethodException: <init> []
                                                                 at java.lang.Class.getConstructor0(Class.java:2327)
                                                                 at java.lang.Class.getDeclaredConstructor(Class.java:2166)
                                                                 at com.didi.virtualapk.utils.Reflector.constructor(Reflector.java:71)
                                                                 at com.didi.virtualapk.PluginManager.hookDataBindingUtil(PluginManager.java:185) 
                                                                 at com.didi.virtualapk.PluginManager.hookCurrentProcess(PluginManager.java:145) 
                                                                 at com.didi.virtualapk.PluginManager.<init>(PluginManager.java:139) 
                                                                 at com.didi.virtualapk.PluginManager.createInstance(PluginManager.java:100) 
                                                                 at com.didi.virtualapk.PluginManager.getInstance(PluginManager.java:85)

**Comment by dtdeng** [comment]
同遇到这个问题，有解决么

**Comment by hp-lxx** [comment]
我这边会是 null。这个有办法解决吗？

**Comment by duoduo4** [comment]
同遇到这个问题，有解决么
