### ISSUE TITLE
宿主与插件之间的传值问题

### ISSUE THREAD

**Issue by VainAnts** [didi/VirtualAPK#305]
- VirtualAPK 运行相关：
1. core version
  compile 'com.didi.virtualapk:core:0.9.6'
2. 问题机型，系统版本
OnePlus3 Android8.0
3. 完整log
 Process: com.aroutertest.virtualapktest, PID: 13657
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.aroutertest.virtualapktest/com.didi.virtualapk.core.A$1}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.CharSequence android.widget.TextView.getText()' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2946)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3046)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1688)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6798)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
        at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:108)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.CharSequence android.widget.TextView.getText()' on a null object reference
        at com.aroutertest.plugindemo.PluginActivity.onCreate(PluginActivity.java:24)
        at android.app.Activity.performCreate(Activity.java:6998)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1230)
        at com.didi.virtualapk.internal.VAInstrumentation.callActivityOnCreate(VAInstrumentation.java:223)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2899)
4. 复现步骤
为了实现宿主与插件通信，引用了相同的aar，但是插件取值值总是取不到，先编译宿主再编译插件和先编译插件再编译数组都尝试过，单纯的运行插件是没有问题的，就是通信取值无法取到。

@superqiaopu

**Comment by VainAnts** [comment]
宿主与插件通信的参考文章：https://blog.csdn.net/a494153985/article/details/84974819
