### ISSUE TITLE
官方demo，启动插件activity报错～

### ISSUE THREAD

**Issue by DaviAndorid** [didi/VirtualAPK#306]
4-18 16:11:17.265 1425-3354/? E/ActivityManager: Sending non-protected broadcast com.vivo.abe.third.lifecontrol from system uid 1000 pkg null
    java.lang.Throwable
        at com.android.server.am.ActivityManagerService.checkBroadcastFromSystem(ActivityManagerService.java:19987)
        at com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:20589)
        at com.android.server.am.ActivityStarter.startActivityLocked(ActivityStarter.java:423)
        at com.android.server.am.ActivityStarter.startActivityMayWait(ActivityStarter.java:1219)
        at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:5412)
        at com.android.server.am.ActivityManagerService.startActivity(ActivityManagerService.java:5346)
        at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:168)
        at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3237)
        at android.os.Binder.execTransact(Binder.java:565)
2019-04-18 16:11:17.340 3221-4026/? E/AppStatisticManager: addLruPkg pkgName = com.didi.virtualapk
2019-04-18 16:11:17.345 3274-4063/? E/AIE-UsageDetailAppCollector: Handle message error -> java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
2019-04-18 16:11:17.347 2274-3538/? E/ProxCoverNoticeService: monitor view is null, no need to update minimum
2019-04-18 16:11:17.509 766-908/? E/ThermalEngine: +++VivoThermal change mode :3 before 
2019-04-18 16:11:17.619 2274-9053/? E/ProxCoverNoticeService: monitor view is null, no need to update minimum
2019-04-18 16:11:18.818 15218-15225/? E/art: Failed sending reply to debugger: Broken pipe
2019-04-18 16:11:18.949 15192-15192/com.didi.virtualapk E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.didi.virtualapk, PID: 15192
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.didi.virtualapk/com.didi.virtualapk.core.A$1}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2749)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2810)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1531)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6292)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:906)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:796)
     Caused by: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
        at android.support.v7.app.AppCompatDelegateImplV7.createSubDecor(AppCompatDelegateImplV7.java:343)
        at android.support.v7.app.AppCompatDelegateImplV7.ensureSubDecor(AppCompatDelegateImplV7.java:312)
        at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:277)
        at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
        at com.didi.virtualapk.demo.aidl.BookManagerActivity.onCreate(BookManagerActivity.java:96)
        at android.app.Activity.performCreate(Activity.java:6788)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1125)
        at com.didi.virtualapk.internal.VAInstrumentation.callActivityOnCreate(VAInstrumentation.java:156)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2702)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2810) 
        at android.app.ActivityThread.-wrap12(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1531) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6292) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:906) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:796) 
2019-04-18 16:11:18.980 1425-5473/? E/ActivityManager: Sending non-protected broadcast com.vivo.abe.messagecenter.exception from system 3221:com.vivo.abe/1000 pkg com.vivo.abe
    java.lang.Throwable
        at com.android.server.am.ActivityManagerService.checkBroadcastFromSystem(ActivityManagerService.java:19982)
        at com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:20498)
        at com.android.server.am.ActivityManagerService.broadcastIntent(ActivityManagerService.java:20680)
        at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:502)
        at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3237)
        at android.os.Binder.execTransact(Binder.java:565)
2019-04-18 16:11:18.980 1425-5473/? E/ActivityManager: Sending non-protected broadcast com.vivo.abe.messagecenter.exception from system 3221:com.vivo.abe/1000 pkg com.vivo.abe
    java.lang.Throwable
        at com.android.server.am.ActivityManagerService.checkBroadcastFromSystem(ActivityManagerService.java:19982)
        at com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:20589)
        at com.android.server.am.ActivityManagerService.broadcastIntent(ActivityManagerService.java:20680)
        at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:502)
        at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3237)
        at android.os.Binder.execTransact(Binder.java:565)
2019-04-18 16:11:19.017 3274-4063/? E/AIE-UsageDetailAppCollector: Handle message error -> java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
2019-04-18 16:11:19.041 2274-2286/? E/ProxCoverNoticeService: monitor view is null, no need to update fullscreen
2019-04-18 16:11:19.273 3376-3429/? E/FontFamily: Error mapping font file /system/fonts/HYQiHei-40.ttf
2019-04-18 16:11:19.273 3376-3429/? E/Launcher.DynamicWeatherIcon: can not get 40s font from system, so use launcher internal font
2019-04-18 16:11:19.285 484-3073/? E/ANDR-PERF-OPTSHANDLER: perf_lock_rel: updated /sys/class/scsi_host/host0/../../../clkscale_enable with 1
     return value 2
2019-04-18 16:11:20.056 2419-6932/? E/LockboxBrokerService: Could not query UDC's getDeviceDataUploadOptInStatus; 15 null
2019-04-18 16:11:20.509 766-908/? E/ThermalEngine: +++VivoThermal change mode :3 before 
2019-04-18 16:11:20.817 1425-2046/? E/TaskPersister: File error accessing recents directory (directory doesn't exist?).
2019-04-18 16:11:23.510 766-908/? E/ThermalEngine: +++VivoThermal change mode :3 before 
2019-04-18 16:11:26.510 766-908/? E/ThermalEngine: +++VivoThermal change mode :3 before 
2019-04-18 16:11:27.172 2466-2466/? E/QtiImsExtUtils: getConfigForPhoneId subId is invalid
2019-04-18 16:11:27.172 2466-2466/? E/QtiImsExtUtils: isCarrierConfigEnabled bundle is null
2019-04-18 16:11:27.174 1425-5473/? E/ActivityManager: Sending non-protected broadcast com.vivo.dismiss.lowpower from system 9958:com.android.systemui/u0a17 pkg com.android.systemui
    java.lang.Throwable
        at com.android.server.am.ActivityManagerService.checkBroadcastFromSystem(ActivityManagerService.java:19982)
        at com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:20589)
        at com.android.server.am.ActivityManagerService.broadcastIntent(ActivityManagerService.java:20680)
        at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:502)
        at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3237)
        at android.os.Binder.execTransact(Binder.java:565)
2019-04-18 16:11:29.511 766-908/? E/ThermalEngine: +++VivoT

**Comment by BeQuietLee** [comment]
你项目里使用了这个主题`AppCompat`但是资源文件里没有对此进行定义

**Comment by DaviAndorid** [comment]
ok
