### ISSUE TITLE
ActivityNotFoundException 插件中的activity调用插件的Activity报错

### ISSUE THREAD

**Issue by hf529270451** [didi/VirtualAPK#309]
我从宿主app跳转插件activity没有问题，从插件activity跳转插件activity报错ActivityNotFoundException，这个怎么排查问题呢

**Comment by shinvi** [comment]
有可能是跳转之前没有加载插件导致的

**Comment by slzGit** [comment]
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.hisense.viewer, PID: 4307
    java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.hisense.viewer/com.didi.virtualapk.core.A$1}: android.content.ActivityNotFoundException: error intent: #Intent;launchFlags=0x10000000;component=com.hisense.viewer/com.didi.virtualapk.core.A%241;B.isPlugin=true;S.target.package=com.hisense.board;S.target.activity=com.hisense.board.ui.BoardActivity;end
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2718)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
     Caused by: android.content.ActivityNotFoundException: error intent: #Intent;launchFlags=0x10000000;component=com.hisense.viewer/com.didi.virtualapk.core.A%241;B.isPlugin=true;S.target.package=com.hisense.board;S.target.activity=com.hisense.board.ui.BoardActivity;end
        at com.didi.virtualapk.internal.VAInstrumentation.newActivity(VAInstrumentation.java:129)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2708)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6541) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

**Comment by slzGit** [comment]
遇到了同样的问题

**Comment by slzGit** [comment]
已解决：
把申请权限的代码注掉就好了：
    /**
     * 动态申请权限
     */
    private void initPermission() {
        String[] permissions = {
                Manifest.permission.INTERNET,
                Manifest.permission.ACCESS_NETWORK_STATE,
                Manifest.permission.MODIFY_AUDIO_SETTINGS,
                Manifest.permission.WRITE_EXTERNAL_STORAGE,
                Manifest.permission.READ_EXTERNAL_STORAGE,
                Manifest.permission.WRITE_SETTINGS,
                Manifest.permission.READ_PHONE_STATE,
                Manifest.permission.ACCESS_WIFI_STATE,
                Manifest.permission.CHANGE_WIFI_STATE,
                Manifest.permission.REQUEST_INSTALL_PACKAGES,
                Manifest.permission.RECEIVE_BOOT_COMPLETED
        };
        ArrayList<String> toApplyList = new ArrayList<>();
        for (String perm : permissions) {
            if (PackageManager.PERMISSION_GRANTED != ContextCompat.checkSelfPermission(this, perm)) {
                toApplyList.add(perm);
            }
        }
        String[] tmpList = new String[toApplyList.size()];
        if (!toApplyList.isEmpty()) {
            ActivityCompat.requestPermissions(this, toApplyList.toArray(tmpList), 123);
        }
    }
