### ISSUE TITLE
ClassNotFoundException

### ISSUE THREAD

**Issue by wuxinrong1981** [didi/VirtualAPK#313]
【问题描述】
在插件apk中进行activity跳转，例如由A跳转到B，
跳转时，A通过intent.PutExtra传递MediaInfo数据类（实现了Parceable接口）到B。
发生ClassNotFound崩溃。

【运行相关】
1. core version：implementation 'com.didi.virtualapk:core:0.9.8'
2. 问题机型和版本：三星 SM-G9500 / Android 9.0
3. 完整log：

java.lang.ClassNotFoundException: com.aliyun.svideo.base.MediaInfo
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:453)
        at android.os.Parcel.readParcelableCreator(Parcel.java:2827)
        at android.os.Parcel.readParcelable(Parcel.java:2781)
        at android.os.Parcel.readValue(Parcel.java:2684)
        at android.os.Parcel.readListInternal(Parcel.java:3114)
        at android.os.Parcel.readArrayList(Parcel.java:2335)
        at android.os.Parcel.readValue(Parcel.java:2705)
        at android.os.Parcel.readArrayMapInternal(Parcel.java:3053)
        at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:288)
        at android.os.BaseBundle.unparcel(BaseBundle.java:232)
        at android.os.BaseBundle.getString(BaseBundle.java:1155)
        at android.content.Intent.getStringExtra(Intent.java:8111)
        at com.android.server.am.ActivityStarter.startActivity(ActivityStarter.java:730)
        at com.android.server.am.ActivityStarter.startActivity(ActivityStarter.java:668)
        at com.android.server.am.ActivityStarter.startActivityMayWait(ActivityStarter.java:1534)
        at com.android.server.am.ActivityStarter.execute(ActivityStarter.java:610)
        at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:6590)
        at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:6481)
        at com.android.server.am.ActivityManagerService.startActivity(ActivityManagerService.java:6472)
        at android.app.IActivityManager$Stub.onTransact$startActivity$(IActivityManager.java:10839)
        at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:111)
        at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:4172)
        at android.os.Binder.execTransact(Binder.java:739)
     Caused by: java.lang.ClassNotFoundException: com.aliyun.svideo.base.MediaInfo
        at java.lang.Class.classForName(Native Method)
        at java.lang.BootClassLoader.findClass(ClassLoader.java:1346)
        at java.lang.BootClassLoader.loadClass(ClassLoader.java:1406)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at java.lang.Class.classForName(Native Method) 
        at java.lang.Class.forName(Class.java:453) 
        at android.os.Parcel.readParcelableCreator(Parcel.java:2827) 
        at android.os.Parcel.readParcelable(Parcel.java:2781) 
        at android.os.Parcel.readValue(Parcel.java:2684) 
        at android.os.Parcel.readListInternal(Parcel.java:3114) 
        at android.os.Parcel.readArrayList(Parcel.java:2335) 
        at android.os.Parcel.readValue(Parcel.java:2705) 
        at android.os.Parcel.readArrayMapInternal(Parcel.java:3053) 
        at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:288) 
        at android.os.BaseBundle.unparcel(BaseBundle.java:232) 
        at android.os.BaseBundle.getString(BaseBundle.java:1155) 
        at android.content.Intent.getStringExtra(Intent.java:8111) 
        at com.android.server.am.ActivityStarter.startActivity(ActivityStarter.java:730) 
        at com.android.server.am.ActivityStarter.startActivity(ActivityStarter.java:668) 
        at com.android.server.am.ActivityStarter.startActivityMayWait(ActivityStarter.java:1534) 
        at com.android.server.am.ActivityStarter.execute(ActivityStarter.java:610) 
        at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:6590) 
        at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:6481) 
        at com.android.server.am.ActivityManagerService.startActivity(ActivityManagerService.java:6472) 
        at android.app.IActivityManager$Stub.onTransact$startActivity$(IActivityManager.java:10839) 
        at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:111) 
        at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:4172) 
        at android.os.Binder.execTransact(Binder.java:739) 
     Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
2019-05-13 18:40:04.844 30022-30022/com.cheetah.cmshow E/Parcel: Class not found when unmarshalling: com.aliyun.svideo.base.MediaInfo
    java.lang.ClassNotFoundException: com.aliyun.svideo.base.MediaInfo
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:453)
        at android.os.Parcel.readParcelableCreator(Parcel.java:2827)
        at android.os.Parcel.readParcelable(Parcel.java:2781)
        at android.os.Parcel.readValue(Parcel.java:2684)
        at android.os.Parcel.readListInternal(Parcel.java:3114)
        at android.os.Parcel.readArrayList(Parcel.java:2335)
        at android.os.Parcel.readValue(Parcel.java:2705)
        at android.os.Parcel.readArrayMapInternal(Parcel.java:3053)
        at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:288)
        at android.os.BaseBundle.unparcel(BaseBundle.java:232)
        at android.os.BaseBundle.getBoolean(BaseBundle.java:894)
        at android.content.Intent.getBooleanExtra(Intent.java:7978)
        at com.didi.virtualapk.internal.utils.PluginUtil.isIntentFromPlugin(PluginUtil.java:73)
        at com.didi.virtualapk.internal.utils.PluginUtil.getComponent(PluginUtil.java:61)
        at com.didi.virtualapk.internal.VAInstrumentation.newActivity(VAInstrumentation.java:107)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3008)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3251)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1948)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7045)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
     Caused by: java.lang.ClassNotFoundException: com.aliyun.svideo.base.MediaInfo

**Comment by wuxinrong1981** [comment]
说明：
1. 在宿主中A调用B并传递Parceable数据类型，没有问题。能正常跳转；
2. 如果将数据类MediaInfo改为实现Serializable，也没有问题，能正常跳转；

**Comment by superqiaopu** [comment]
暂不支持。目前识别占位activity的方式是设extra标记，根据标记的package来匹配所属plugin，得到plugin的classloader，而读取extra时会立即触发unparcel，此时classloader还未替换成plugin的classloader，所以失败。
可以考虑优化识别占位activity的方式，不使用extra标记。

**Comment by wuxinrong1981** [comment]
是的。当时也是怀疑ClassLoader没有替换的原因。
但是插件框架没有提供替换ClassLoader的api。
请问一下：不适用extra标记的话，在Activity跳转期间，如何传递Parceable数据类呢？

**Comment by superqiaopu** [comment]
com.didi.virtualapk:core:0.9.9.1-dev 已优化。

**Comment by wuxinrong1981** [comment]
@superqiaopu 感谢滴滴的伙伴的热心、即时的修复问题。再次感谢。

**Comment by yatoooon** [comment]
用的0.9.9.1-dev 还是会出现这种问题    在android 9.0上 插件之间传递Parceable数据类 报 Class not found when unmarshalling

**Comment by wuxinrong1981** [comment]
我们这边的使用0.9.9.1-dev，确实不报这个问题了。






------------------ 原始邮件 ------------------
发件人: "yatoooon"<notifications@github.com>;
发送时间: 2019年5月23日(星期四) 中午12:08
收件人: "didi/VirtualAPK"<VirtualAPK@noreply.github.com>;
抄送: "吴新荣"<28124681@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [didi/VirtualAPK] ClassNotFoundException (#313)




用的0.9.9.1-dev 还是会出现这种问题    在android 9.0上 插件之间传递Parceable数据类 报 Class not found when unmarshalling

**Comment by BeQuietLee** [comment]
@superqiaopu 请问 0.9.9.1-dev 的提交在哪里可以看到？
