### ISSUE TITLE
插件构建失败

### ISSUE THREAD

**Issue by BlackMambaK** [didi/VirtualAPK#324]
执行./gradlew assemblePlugin会构建失败，日志如下，但是执行./gradlew _assemblePlugin就可以。

FAILURE: Build failed with an exception.

* What went wrong:
Failed to notify task execution listener.
> Required entry 'text_color' but got 'text_pressed', This is seems to unsupport the buildToolsRevision: 28.0.3.

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.internal.event.ListenerNotificationException: Failed to notify task execution listener.
        at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:86)
        at org.gradle.internal.event.DefaultListenerManager$EventBroadcast$ListenerDispatch.dispatch(DefaultListenerManager.java:340)
        at org.gradle.internal.event.DefaultListenerManager$EventBroadcast$ListenerDispatch.dispatch(DefaultListenerManager.java:327)
        at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:42)
        at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:230)
        at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:149)
        at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:140)
        at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:37)
        at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
        at com.sun.proxy.$Proxy83.afterExecute(Unknown Source)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.run(EventFiringTaskExecuter.java:57)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:46)
        at org.gradle.execution.taskgraph.LocalTaskInfoExecutor.execute(LocalTaskInfoExecutor.java:42)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:277)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:262)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:135)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:130)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.execute(DefaultTaskPlanExecutor.java:200)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.executeWithWork(DefaultTaskPlanExecutor.java:191)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.run(DefaultTaskPlanExecutor.java:130)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: java.lang.Exception: Required entry 'text_color' but got 'text_pressed', This is seems to unsupport the buildToolsRevision: 28.0.3.
        at com.didi.virtualapk.aapt.ArscEditor$_slice_closure2$_closure13$_closure14.doCall(ArscEditor.groovy:141)
        at com.didi.virtualapk.aapt.ArscEditor$_slice_closure2$_closure13.doCall(ArscEditor.groovy:121)
        at com.didi.virtualapk.aapt.ArscEditor$_slice_closure2.doCall(ArscEditor.groovy:116)
        at com.didi.virtualapk.aapt.ArscEditor.slice(ArscEditor.groovy:89)
        at com.didi.virtualapk.aapt.ArscEditor$slice.call(Unknown Source)
        at com.didi.virtualapk.aapt.Aapt.filterPackage(Aapt.groovy:50)
        at com.didi.virtualapk.aapt.Aapt$filterPackage$0.call(Unknown Source)
        at com.didi.virtualapk.hooker.ProcessResourcesHooker.repackage(ProcessResourcesHooker.groovy:128)
        at com.didi.virtualapk.hooker.ProcessResourcesHooker$repackage.callCurrent(Unknown Source)
        at com.didi.virtualapk.hooker.ProcessResourcesHooker.afterTaskExecute(ProcessResourcesHooker.groovy:68)
        at com.didi.virtualapk.hooker.ProcessResourcesHooker.afterTaskExecute(ProcessResourcesHooker.groovy)
        at com.didi.virtualapk.hooker.GradleTaskHooker$afterTaskExecute$0.call(Unknown Source)
        at com.didi.virtualapk.hooker.GradleTaskHooker$afterTaskExecute$0.call(Unknown Source)
        at com.didi.virtualapk.hooker.TaskHookerManager$VirtualApkTaskListener.afterExecute(TaskHookerManager.groovy:66)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.event.DefaultListenerManager$ListenerDetails.dispatch(DefaultListenerManager.java:370)
        at org.gradle.internal.event.DefaultListenerManager$ListenerDetails.dispatch(DefaultListenerManager.java:352)
        at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:58)
        ... 27 more

**Comment by jt1024** [comment]
遇到同样的问题，请问解决了吗

**Comment by yudesong** [comment]
将 build.gradle 里面的buildToolsVersion VERSION_BUILD_TOOLS 删除就可以了。
