### ISSUE TITLE
打开今日头条apk报找不到类

### ISSUE THREAD

**Issue by tjt852** [didi/VirtualAPK#341]
Didn't find class "com.google.ads.conversiontracking.InstallReceiver" on path: DexPathList[[zip file "/storage/emulated/0/com.ss.android.article.news_7.3.1_731.apk"],nativeLibraryDirectories=[/data/user/0/com.didi.virtualapk/app_valibs, /system/lib]]

**Comment by tjt852** [comment]
2019-08-26 14:47:08.921 1177-1678/? W/AccountManagerService: insertAccountIntoDatabase: Account {name=今日头条, type=com.ss.android.article.news}, skipping since the account already exists
2019-08-26 14:47:09.995 27055-27055/com.didi.virtualapk W/System.err: java.lang.ClassNotFoundException: Didn't find class "com.google.ads.conversiontracking.InstallReceiver" on path: DexPathList[[zip file "/storage/emulated/0/com.ss.android.article.news_7.3.1_731.apk"],nativeLibraryDirectories=[/data/user/0/com.didi.virtualapk/app_valibs, /system/lib]]
2019-08-26 14:47:10.000 27055-27055/com.didi.virtualapk W/System.err:     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
2019-08-26 14:47:10.005 27055-27055/com.didi.virtualapk W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
2019-08-26 14:47:10.009 27055-27055/com.didi.virtualapk W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
2019-08-26 14:47:10.013 27055-27055/com.didi.virtualapk W/System.err:     at com.didi.virtualapk.internal.LoadedPlugin.<init>(LoadedPlugin.java:227)
2019-08-26 14:47:10.017 27055-27055/com.didi.virtualapk W/System.err:     at com.didi.virtualapk.PluginManager.createLoadedPlugin(PluginManager.java:177)
2019-08-26 14:47:10.021 27055-27055/com.didi.virtualapk W/System.err:     at com.didi.virtualapk.PluginManager.loadPlugin(PluginManager.java:318)
2019-08-26 14:47:10.024 27055-27055/com.didi.virtualapk W/System.err:     at com.didi.virtualapk.MainActivity.loadPlugin(MainActivity.java:143)
2019-08-26 14:47:10.027 27055-27055/com.didi.virtualapk W/System.err:     at com.didi.virtualapk.MainActivity.onCreate(MainActivity.java:53)
2019-08-26 14:47:10.029 27055-27055/com.didi.virtualapk W/System.err:     at android.app.Activity.performCreate(Activity.java:7144)
2019-08-26 14:47:10.032 27055-27055/com.didi.virtualapk W/System.err:     at android.app.Activity.performCreate(Activity.java:7135)
2019-08-26 14:47:10.034 27055-27055/com.didi.virtualapk W/System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
2019-08-26 14:47:10.037 27055-27055/com.didi.virtualapk W/System.err:     at com.didi.virtualapk.internal.VAInstrumentation.callActivityOnCreate(VAInstrumentation.java:156)
2019-08-26 14:47:10.040 27055-27055/com.didi.virtualapk W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2931)
2019-08-26 14:47:10.043 27055-27055/com.didi.virtualapk W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3086)
2019-08-26 14:47:10.047 27055-27055/com.didi.virtualapk W/System.err:     at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
2019-08-26 14:47:10.049 27055-27055/com.didi.virtualapk W/System.err:     at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
2019-08-26 14:47:10.051 27055-27055/com.didi.virtualapk W/System.err:     at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
2019-08-26 14:47:10.053 27055-27055/com.didi.virtualapk W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
2019-08-26 14:47:10.055 27055-27055/com.didi.virtualapk W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:106)
2019-08-26 14:47:10.057 27055-27055/com.didi.virtualapk W/System.err:     at android.os.Looper.loop(Looper.java:193)
2019-08-26 14:47:10.058 27055-27055/com.didi.virtualapk W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6718)
2019-08-26 14:47:10.060 27055-27055/com.didi.virtualapk W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2019-08-26 14:47:10.062 27055-27055/com.didi.virtualapk W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
2019-08-26 14:47:10.065 27055-27055/com.didi.virtualapk W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
    
    --------- beginning of system
