### ISSUE TITLE
java.lang.RuntimeException: Failure from system

### ISSUE THREAD

**Issue by nnjun** [didi/VirtualAPK#369]
CPU_ABI=armeabi-v7a
FINGERPRINT=OPPO/PBEM00/PBEM00:9

java.lang.RuntimeException: Failure from system
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1677)
	at com.didi.virtualapk.internal.VAInstrumentation.execStartActivity(:75)
	at android.app.Activity.startActivityForResult(Activity.java:4709)
	at android.support.v4.app.BaseFragmentActivityApi16.startActivityForResult(:54)
	at android.support.v4.app.FragmentActivity.startActivityForResult(:68)
	at android.app.Activity.startActivityForResult(Activity.java:4655)
	at android.support.v4.app.FragmentActivity.startActivityForResult(:751)
	at android.app.Activity.startActivity(Activity.java:5028)
	at android.app.Activity.startActivity(Activity.java:4996)

------------------------------------------------------------------

Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.am.ActivityStackSupervisor.checkStartAnyActivityPermission(ActivityStackSupervisor.java:1960)
	at com.android.server.am.ActivityStarter.startActivity(ActivityStarter.java:1255)
	at com.android.server.am.ActivityStarter.startActivity(ActivityStarter.java:694)
	at com.android.server.am.ActivityStarter.startActivityMayWait(ActivityStarter.java:2357)
	at com.android.server.am.ActivityStarter.execute(ActivityStarter.java:632)

android.os.RemoteException: Remote stack trace:
	at com.android.server.am.ActivityStackSupervisor.checkStartAnyActivityPermission(ActivityStackSupervisor.java:1960)
	at com.android.server.am.ActivityStarter.startActivity(ActivityStarter.java:1255)
	at com.android.server.am.ActivityStarter.startActivity(ActivityStarter.java:694)
	at com.android.server.am.ActivityStarter.startActivityMayWait(ActivityStarter.java:2357)
	at com.android.server.am.ActivityStarter.execute(ActivityStarter.java:632)

**Comment by Quintessential-Maker** [comment]
**Hey is your issue resoled?**

**Comment by nnjun** [comment]
> **Hey is your issue resoled?**

This project has been abandoned and is not recommended.
