### ISSUE TITLE
  java.lang.IncompatibleClassChangeError: com.didi.virtualapk.demo.aidl.BookManagerActivity

### ISSUE THREAD

**Issue by AllenCoder** [didi/VirtualAPK#38]
只修改了  app 和PluginDemo的sdk版本 ，
```
   compileSdkVersion 25
    buildToolsVersion "25.0.2"

```
加载插件时闪退 
测试机型 小米5C 
              Android 版本 6.0 
               mui 8.1

```java

07-03 19:49:56.378 2772-2772/com.didi.virtualapk E/AndroidRuntime: FATAL EXCEPTION: main
                                                                   Process: com.didi.virtualapk, PID: 2772
                                                                   java.lang.IncompatibleClassChangeError: com.didi.virtualapk.demo.aidl.BookManagerActivity
                                                                       at dalvik.system.DexFile.defineClassNative(Native Method)
                                                                       at dalvik.system.DexFile.defineClass(DexFile.java:226)
                                                                       at dalvik.system.DexFile.loadClassBinaryName(DexFile.java:219)
                                                                       at dalvik.system.DexPathList.findClass(DexPathList.java:338)
                                                                       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:54)
                                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                                       at android.app.Instrumentation.newActivity(Instrumentation.java:1067)
                                                                       at com.didi.virtualapk.internal.VAInstrumentation.newActivity(VAInstrumentation.java:101)
                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2324)
                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2483)
                                                                       at android.app.ActivityThread.access$900(ActivityThread.java:153)
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1349)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                       at android.os.Looper.loop(Looper.java:148)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5441)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)
```

**Comment by lypandroidex** [comment]
该问题解决了么。

**Comment by AllenCoder** [comment]
将版本切回与Demo版本一致，就可以正常运行了
