### ISSUE TITLE
插件apk 不能实例化控件

### ISSUE THREAD

**Issue by ciferLiao** [didi/VirtualAPK#40]
`07-04 10:22:39.895 27880-27880/com.didi.virtualapk E/AndroidRuntime: FATAL EXCEPTION: main
                                                                     Process: com.didi.virtualapk, PID: 27880
                                                                     java.lang.RuntimeException: Unable to start activity ComponentInfo{com.didi.virtualapk/com.didi.virtualapk.core.A$1}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setText(java.lang.CharSequence)' on a null object reference
                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2679)
                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2750)
                                                                         at android.app.ActivityThread.-wrap13(ActivityThread.java)
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1595)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:111)
                                                                         at android.os.Looper.loop(Looper.java:207)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5966)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:749)
                                                                      Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setText(java.lang.CharSequence)' on a null object reference
                                                                         at mejust.mytest.TActivity.onCreate(TActivity.java:41)
                                                                         at android.app.Activity.performCreate(Activity.java:6300)
                                                                         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1113)
                                                                         at com.didi.virtualapk.internal.VAInstrumentation.callActivityOnCreate(VAInstrumentation.java:141)
                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2632)
                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2750) 
                                                                         at android.app.ActivityThread.-wrap13(ActivityThread.java) 
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1595) 
                                                                         at android.os.Handler.dispatchMessage(Handler.java:111) 
                                                                         at android.os.Looper.loop(Looper.java:207) 
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5966) 
                                                                         at java.lang.reflect.Method.invoke(Native Method) 
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888) 
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:749) `

打开新建插件apk报错，没有实例化控件，单独运行是没有错误的，如果将插件apk控件实例化注释掉，是可以运行，也能收到传递的值。
`virtualApk {
    packageId = 0x6f // the package id of Resources.
    targetHost = 'com.didi.virtualapk/VirtualAPK/app' // the path of application module in host project.
 applyHostMapping = true //optional, default value: true.
}`
已在 build.gradle 里添加了如上代码，还是不知道原因，

**Comment by renlei0109** [comment]
楼主问题解决了么，我还是不行

**Comment by gnmmdk** [comment]
我也是有遇到获取控件失败，不过改了下packageId就可以，packageId应该在0x01和0x7F之间(不能包含),packageId默认的值就是0x7F,系统应用的话就是0x01(视具体系统而定）。不过你好像不是因为这个原因。

**Comment by XiuLin** [comment]
注意buildtools版本，注意使用相同版本的依赖的库。
