### ISSUE TITLE
加载直接奔溃

### ISSUE THREAD

**Issue by wuxiaojun123** [didi/VirtualAPK#45]
java.lang.IllegalAccessError: Class ref in pre-verified class resolved to unexpected implementation
                                                                         at dalvik.system.DexFile.defineClassNative(Native Method)
                                                                         at dalvik.system.DexFile.defineClass(DexFile.java:222)
                                                                         at dalvik.system.DexFile.loadClassBinaryName(DexFile.java:215)
                                                                         at dalvik.system.DexPathList.findClass(DexPathList.java:322)
                                                                         at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:54)
                                                                         at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
                                                                         at java.lang.ClassLoader.loadClass(ClassLoader.java:491)
                                                                         at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
                                                                         at android.app.Instrumentation.newActivity(Instrumentation.java:1067)
                                                                         at com.didi.virtualapk.internal.VAInstrumentation.newActivity(VAInstrumentation.java:101)
                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2403)
                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2607)
                                                                         at android.app.ActivityThread.access$900(ActivityThread.java:174)
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1325)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                         at android.os.Looper.loop(Looper.java:146)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5756)
                                                                         at java.lang.reflect.Method.invokeNative(Native Method)
                                                                         at java.lang.reflect.Method.invoke(Method.java:515)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
                                                                         at dalvik.system.NativeStart.main(Native Method)

**Comment by Ahuanghaifeng** [comment]
一样的问题，楼主解决没有

**Comment by msdgwzhy6** [comment]
你的问题是插件生成有问题 ，请按照wiki里的生成插件方式操作
