### ISSUE TITLE
按照正常流程走的，解析不正常

### ISSUE THREAD

**Issue by fuzhijun52058237** [didi/VirtualAPK#54]
W/System.err: android.content.pm.PackageParser$PackageParserException: Failed to parse /storage/emulated/0/Test.apk
07-06 20:29:43.306 1080-1080/? W/System.err:     at android.content.pm.PackageParser.parseApkLite(PackageParser.java:1415)
07-06 20:29:43.306 1080-1080/? W/System.err:     at android.content.pm.PackageParser.parseMonolithicPackageLite(PackageParser.java:728)
07-06 20:29:43.306 1080-1080/? W/System.err:     at android.content.pm.PackageParser.parseMonolithicPackage(PackageParser.java:919)
07-06 20:29:43.306 1080-1080/? W/System.err:     at android.content.pm.PackageParser.parsePackage(PackageParser.java:834)
07-06 20:29:43.306 1080-1080/? W/System.err:     at android.content.pm.PackageParser.parsePackage(PackageParser.java:827)
07-06 20:29:43.306 1080-1080/? W/System.err:     at com.didi.virtualapk.a.e.a(PackageParserCompat.java:44)
07-06 20:29:43.306 1080-1080/? W/System.err:     at com.didi.virtualapk.a.b.a(PackageParserCompat.java:32)
07-06 20:29:43.306 1080-1080/? W/System.err:     at com.didi.virtualapk.internal.c.<init>(LoadedPlugin.java:150)
07-06 20:29:43.306 1080-1080/? W/System.err:     at com.didi.virtualapk.internal.c.a(LoadedPlugin.java:78)
07-06 20:29:43.306 1080-1080/? W/System.err:     at com.didi.virtualapk.b.a(PluginManager.java:202)
07-06 20:29:43.306 1080-1080/? W/System.err:     at com.didi.virtualapk.MainActivity.a(MainActivity.java:77)
07-06 20:29:43.306 1080-1080/? W/System.err:     at com.didi.virtualapk.MainActivity.onCreate(MainActivity.java:38)
07-06 20:29:43.306 1080-1080/? W/System.err:     at android.app.Activity.performCreate(Activity.java:6910)
07-06 20:29:43.306 1080-1080/? W/System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1123)
07-06 20:29:43.306 1080-1080/? W/System.err:     at com.didi.virtualapk.internal.VAInstrumentation.callActivityOnCreate(VAInstrumentation.java:141)
07-06 20:29:43.306 1080-1080/? W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2746)
07-06 20:29:43.306 1080-1080/? W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2864)
07-06 20:29:43.306 1080-1080/? W/System.err:     at android.app.ActivityThread.-wrap12(ActivityThread.java)
07-06 20:29:43.306 1080-1080/? W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1567)
07-06 20:29:43.306 1080-1080/? W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
07-06 20:29:43.306 1080-1080/? W/System.err:     at android.os.Looper.loop(Looper.java:156)
07-06 20:29:43.306 1080-1080/? W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6524)
07-06 20:29:43.306 1080-1080/? W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
07-06 20:29:43.306 1080-1080/? W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
07-06 20:29:43.306 1080-1080/? W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)
07-06 20:29:43.306 1080-1080/? W/System.err: Caused by: java.io.FileNotFoundException: AndroidManifest.xml
07-06 20:29:43.306 1080-1080/? W/System.err:     at android.content.res.AssetManager.openXmlAssetNative(Native Method)
07-06 20:29:43.306 1080-1080/? W/System.err:     at android.content.res.AssetManager.openXmlBlockAsset(AssetManager.java:862)
07-06 20:29:43.306 1080-1080/? W/System.err:     at android.content.res.AssetManager.openXmlResourceParser(AssetManager.java:830)
07-06 20:29:43.306 1080-1080/? W/System.err:     at android.content.pm.PackageParser.parseApkLite(PackageParser.java:1391)
07-06 20:29:43.306 1080-1080/? W/System.err: 	... 24 more

**Comment by fuzhijun52058237** [comment]
测试手机为华为P9

**Comment by singwhatiwanna** [comment]
@fuzhijun52058237 请帮忙核对下，插件apk是否有效，检测插件apk中是否有AndroidManifest.xml文件。

Caused by: java.io.FileNotFoundException: AndroidManifest.xml

**Comment by fuzhijun52058237** [comment]
![a3098191-6fa2-40fe-8739-dcf2982abc41](https://user-images.githubusercontent.com/4945960/27994796-fdfcd61c-64f6-11e7-9d6f-399b5380fd89.png)

我这边看到是存在的

**Comment by fuzhijun52058237** [comment]
@singwhatiwanna

**Comment by CeAlong** [comment]
这怎么解决的, 华为荣耀9也是这个问题

**Comment by xinnian25** [comment]
有人解决吗？我也遇到了，荣耀8机子

**Comment by superqiaopu** [comment]
请提供下完整的log日志，范围从app启动至报错，log级别V，所有进程。
华为机型开启V级别log，请参考 http://blog.csdn.net/tenfyguo/article/details/46694729

**Comment by DCRain** [comment]
同样的问题，找不到AndroidManifest.xml，但是插件中是包含AndroidManifest.xml文件的。测试机：Android模拟器，Nexus 6p都不行。日志如下：

05-18 18:40:59.620 5635-5635/? I/art: Not late-enabling -Xcheck:jni (already on)
05-18 18:40:59.620 5635-5635/? W/art: Unexpected CPU variant for X86 using defaults: x86
05-18 18:40:59.683 5635-5635/com.uusnail.tinkertest W/System: ClassLoader referenced unknown path: /data/app/com.uusnail.tinkertest-2/lib/x86
05-18 18:40:59.815 5635-5635/com.uusnail.tinkertest W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
05-18 18:41:00.048 5635-5652/com.uusnail.tinkertest I/OpenGLRenderer: Initialized EGL, version 1.4
05-18 18:41:00.048 5635-5652/com.uusnail.tinkertest D/OpenGLRenderer: Swap behavior 1
05-18 18:41:00.048 5635-5652/com.uusnail.tinkertest W/OpenGLRenderer: Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
05-18 18:41:00.049 5635-5652/com.uusnail.tinkertest D/OpenGLRenderer: Swap behavior 0
05-18 18:41:00.053 5635-5652/com.uusnail.tinkertest D/EGL_emulation: eglCreateContext: 0x9a66c180: maj 3 min 0 rcv 3
05-18 18:41:00.083 5635-5652/com.uusnail.tinkertest D/EGL_emulation: eglMakeCurrent: 0x9a66c180: ver 3 0 (tinfo 0x9d6cda20)
05-18 18:41:00.110 5635-5652/com.uusnail.tinkertest D/EGL_emulation: eglMakeCurrent: 0x9a66c180: ver 3 0 (tinfo 0x9d6cda20)
05-18 18:41:11.245 5635-5635/com.uusnail.tinkertest W/zipro: Error opening archive /storage/emulated/0/Test.apk: I/O Error
05-18 18:41:11.245 5635-5635/com.uusnail.tinkertest D/asset: failed to open Zip archive '/storage/emulated/0/Test.apk'
05-18 18:41:11.246 5635-5635/com.uusnail.tinkertest D/AndroidRuntime: Shutting down VM
05-18 18:41:11.248 5635-5635/com.uusnail.tinkertest E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.uusnail.tinkertest, PID: 5635
    java.lang.IllegalStateException: Could not execute method for android:onClick
        at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:389)
        at android.view.View.performClick(View.java:5637)
        at android.view.View$PerformClick.run(View.java:22429)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:384)
        at android.view.View.performClick(View.java:5637) 
        at android.view.View$PerformClick.run(View.java:22429) 
        at android.os.Handler.handleCallback(Handler.java:751) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6119) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776) 
     Caused by: android.content.pm.PackageParser$PackageParserException: Failed to parse /storage/emulated/0/Test.apk
        at android.content.pm.PackageParser.parseApkLite(PackageParser.java:1352)
        at android.content.pm.PackageParser.parseMonolithicPackageLite(PackageParser.java:704)
        at android.content.pm.PackageParser.parseMonolithicPackage(PackageParser.java:874)
        at android.content.pm.PackageParser.parsePackage(PackageParser.java:801)
        at com.didi.virtualapk.utils.PackageParserCompat$PackageParserV24.parsePackage(PackageParserCompat.java:44)
        at com.didi.virtualapk.utils.PackageParserCompat.parsePackage(PackageParserCompat.java:32)
        at com.didi.virtualapk.internal.LoadedPlugin.<init>(LoadedPlugin.java:149)
        at com.didi.virtualapk.internal.LoadedPlugin.create(LoadedPlugin.java:78)
        at com.didi.virtualapk.PluginManager.loadPlugin(PluginManager.java:219)
        at com.uusnail.tinkertest.MainActivity.onClick(MainActivity.kt:22)
        at java.lang.reflect.Method.invoke(Native Method) 
        at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:384) 
        at android.view.View.performClick(View.java:5637) 
        at android.view.View$PerformClick.run(View.java:22429) 
        at android.os.Handler.handleCallback(Handler.java:751) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6119) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776) 
     Caused by: java.io.FileNotFoundException: AndroidManifest.xml
        at android.content.res.AssetManager.openXmlAssetNative(Native Method)
        at android.content.res.AssetManager.openXmlBlockAsset(AssetManager.java:519)
        at android.content.res.AssetManager.openXmlResourceParser(AssetManager.java:487)
        at android.content.pm.PackageParser.parseApkLite(PackageParser.java:1328)
        at android.content.pm.PackageParser.parseMonolithicPackageLite(PackageParser.java:704) 
        at android.content.pm.PackageParser.parseMonolithicPackage(PackageParser.java:874) 
        at android.content.pm.PackageParser.parsePackage(PackageParser.java:801) 
        at com.didi.virtualapk.utils.PackageParserCompat$PackageParserV24.parsePackage(PackageParserCompat.java:44) 
        at com.didi.virtualapk.utils.PackageParserCompat.parsePackage(PackageParserCompat.java:32) 
        at com.didi.virtualapk.internal.LoadedPlugin.<init>(LoadedPlugin.java:149) 
        at com.didi.virtualapk.internal.LoadedPlugin.create(LoadedPlugin.java:78) 
        at com.didi.virtualapk.PluginManager.loadPlugin(PluginManager.java:219) 
        at com.uusnail.tinkertest.MainActivity.onClick(MainActivity.kt:22) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:384) 
        at android.view.View.performClick(View.java:5637) 
        at android.view.View$PerformClick.run(View.java:22429) 
        at android.os.Handler.handleCallback(Handler.java:751) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6119) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by minwenping** [comment]
华为荣耀8，android8.0系统遇到同样的问题，log如下：
 Failed to parse /storage/emulated/0/pluginradio_release.apk
                                                                                   java.io.FileNotFoundException: AndroidManifest.xml
                                                                                       at android.content.res.AssetManager.openXmlAssetNative(Native Method)
                                                                                       at android.content.res.AssetManager.openXmlBlockAsset(AssetManager.java:862)
                                                                                       at android.content.res.AssetManager.openXmlResourceParser(AssetManager.java:830)
                                                                                       at android.content.pm.PackageParser.parseApkLite(PackageParser.java:1771)
                                                                                       at android.content.pm.PackageParser.parseMonolithicPackageLite(PackageParser.java:913)
..........................................后面log就不在打印了.................................
然后定位到最终错误的位置调用的方法如下：
` /**
     * {@hide}
     * Retrieve a non-asset as a compiled XML file.  Not for use by
     * applications.
     * 
     * @param cookie Identifier of the package to be opened.
     * @param fileName Name of the asset to retrieve.
     */
    /*package*/ final XmlBlock openXmlBlockAsset(int cookie, String fileName)
        throws IOException {
        synchronized (this) {
            if (!mOpen) {
                throw new RuntimeException("Assetmanager has been closed");
            }
            long xmlBlock = openXmlAssetNative(cookie, fileName);
            if (xmlBlock != 0) {
                XmlBlock res = new XmlBlock(this, xmlBlock);
                incRefsLocked(res.hashCode());
                return res;
            }
        }
        throw new FileNotFoundException("Asset XML file: " + fileName);
    }`
这是android      8.0的framework的assetMananger的源码，调用的openXmlAssetNative方法返回值不是0，就跑出这样的错误，不知楼主可否hook掉native层的返回值解决这个问题@singwhatiwanna@CeAlong

**Comment by darrenjh** [comment]
已解决，插件打包要配置签名

**Comment by MrZhangSan** [comment]
@darrenjh 你的打包命令怎么写的，我这边也有同样问题，可以发一下吗？
