### ISSUE TITLE
资源文件找不到。。。

### ISSUE THREAD

**Issue by maolubin** [didi/VirtualAPK#61]
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.didi.virtualapk/com.didi.virtualapk.core.A$1}: android.content.res.Resources$NotFoundException: File 搜索 from xml type layout resource ID #0x7f060008
                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2484)
                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2544)
                                                                         at android.app.ActivityThread.access$900(ActivityThread.java:150)
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1394)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                         at android.os.Looper.loop(Looper.java:168)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5845)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:797)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:687)
                                                                      Caused by: android.content.res.Resources$NotFoundException: File 搜索 from xml type layout resource ID #0x7f060008
                                                                         at android.content.res.Resources.loadXmlResourceParser(Resources.java:2836)
                                                                         at android.content.res.Resources.loadXmlResourceParser(Resources.java:2791)
                                                                         at android.content.res.Resources.getLayout(Resources.java:1173)
                                                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:421)
                                                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
                                                                         at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:411)
                                                                         at android.app.Activity.setContentView(Activity.java:2177)
                                                                         at com.businesshall.activity.SplashActivity.onCreate(SplashActivity.java:30)
                                                                         at android.app.Activity.performCreate(Activity.java:6248)
                                                                         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1125)
                                                                         at com.didi.virtualapk.internal.VAInstrumentation.callActivityOnCreate(VAInstrumentation.java:141)
                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2437)
                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2544) 
                                                                         at android.app.ActivityThread.access$900(ActivityThread.java:150) 
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1394) 
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                         at android.os.Looper.loop(Looper.java:168) 
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5845) 
                                                                         at java.lang.reflect.Method.invoke(Native Method) 
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:797) 
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:687) 
                                                                      Caused by: java.io.FileNotFoundException: 搜索
                                                                         at android.content.res.AssetManager.openXmlAssetNative(Native Method)
                                                                         at android.content.res.AssetManager.openXmlBlockAsset(AssetManager.java:508)
                                                                         at android.content.res.Resources.loadXmlResourceParser(Resources.java:2818)
                                                                         at android.content.res.Resources.loadXmlResourceParser(Resources.java:2791) 
                                                                         at android.content.res.Resources.getLayout(Resources.java:1173) 
                                                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:421) 
                                                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
                                                                         at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:411) 
                                                                         at android.app.Activity.setContentView(Activity.java:2177) 
                                                                         at com.businesshall.activity.SplashActivity.onCreate(SplashActivity.java:30) 
                                                                         at android.app.Activity.performCreate(Activity.java:6248) 
                                                                         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1125) 
                                                                         at com.didi.virtualapk.internal.VAInstrumentation.callActivityOnCreate(VAInstrumentation.java:141) 
                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2437) 
                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2544) 
                                                                         at android.app.ActivityThread.access$900(ActivityThread.java:150) 
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1394) 
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                         at android.os.Looper.loop(Looper.java:168) 
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5845) 
                                                                         at java.lang.reflect.Method.invoke(Native Method) 
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:797) 
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:687)

**Comment by BeEagle** [comment]
@maolubin 请教您这边解决了么？

**Comment by XiuLin** [comment]
插件的资源id设置是不是有问题
