### ISSUE TITLE
如何卸载插件？

### ISSUE THREAD

**Issue by changkai244** [didi/VirtualAPK#62]
第一次运行成功了，然后将程序退出以后再次打开又报错？
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.didi.virtualapk/com.didi.virtualapk.MainActivity}: android.view.InflateException: Binary XML file line #36: Error inflating class <unknown>
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2702)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2767)
                                                     at android.app.ActivityThread.access$900(ActivityThread.java:177)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1449)
                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                     at android.os.Looper.loop(Looper.java:145)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5981)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at java.lang.reflect.Method.invoke(Method.java:372)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
                                                  Caused by: android.view.InflateException: Binary XML file line #36: Error inflating class <unknown>
                                                     at android.view.LayoutInflater.createView(LayoutInflater.java:640)
                                                     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:750)
                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:813)
                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:821)
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:511)
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:415)
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:366)
                                                     at android.support.v7.app.AppCompatDelegateImplV7.ensureSubDecor(AppCompatDelegateImplV7.java:299)
                                                     at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:246)
                                                     at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:106)
                                                     at com.didi.virtualapk.MainActivity.onCreate(MainActivity.java:28)
                                                     at android.app.Activity.performCreate(Activity.java:6289)
                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
                                                     at com.didi.virtualapk.internal.VAInstrumentation.callActivityOnCreate(VAInstrumentation.java:141)
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2655)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2767) 
                                                     at android.app.ActivityThread.access$900(ActivityThread.java:177) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1449) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                     at android.os.Looper.loop(Looper.java:145) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:5981) 
                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                     at java.lang.reflect.Method.invoke(Method.java:372) 
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194) 
                                                  Caused by: java.lang.reflect.InvocationTargetException
                                                     at java.lang.reflect.Constructor.newInstance(Native Method)
                                                     at java.lang.reflect.Constructor.newInstance(Constructor.java:288)

**Comment by changkai244** [comment]
感觉是程序进程 没有完全退出 我完全退出进程以后就不报错了。。并且我开始运行的时候plug app项目使用AppCompatActivity就无法启动会报错“You need to use a Theme.AppCompat theme (or descendant) with this activity.” 将其改成Activity就没有问题，不知道是否是不支持AppCompatActivity，谢谢！

**Comment by chenenyu** [comment]
生成插件的过程请按照wiki来
