### ISSUE TITLE
一次性加载了3个插件，点击插件就奔溃

### ISSUE THREAD

**Issue by maolubin** [didi/VirtualAPK#63]
java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.didi.virtualapk/com.didi.virtualapk.core.A$1}: java.lang.ClassNotFoundException: Didn't find class "com.didi.virtualapk.core.A$1" on path: DexPathList[[zip file "/data/app/com.didi.virtualapk-2/base.apk"],nativeLibraryDirectories=[/data/app/com.didi.virtualapk-2/lib/arm, /data/app/com.didi.virtualapk-2/base.apk!/lib/armeabi, /vendor/lib, /system/lib]]
                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2395)
                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2544)
                                                                         at android.app.ActivityThread.access$900(ActivityThread.java:150)
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1394)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                         at android.os.Looper.loop(Looper.java:168)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5845)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:797)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:687)
                                                                      Caused by: java.lang.ClassNotFoundException: Didn't find class "com.didi.virtualapk.core.A$1" on path: DexPathList[[zip file "/data/app/com.didi.virtualapk-2/base.apk"],nativeLibraryDirectories=[/data/app/com.didi.virtualapk-2/lib/arm, /data/app/com.didi.virtualapk-2/base.apk!/lib/armeabi, /vendor/lib, /system/lib]]
                                                                         at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                         at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                                         at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                                         at android.app.Instrumentation.newActivity(Instrumentation.java:1085)
                                                                         at com.didi.virtualapk.internal.VAInstrumentation.newActivity(VAInstrumentation.java:115)
                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2385)
                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2544) 
                                                                         at android.app.ActivityThread.access$900(ActivityThread.java:150) 
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1394) 
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                         at android.os.Looper.loop(Looper.java:168) 
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5845) 
                                                                         at java.lang.reflect.Method.invoke(Native Method) 
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:797) 
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:687) 
                                                                     	Suppressed: java.lang.ClassNotFoundException: com.didi.virtualapk.core.A$1
                                                                         at java.lang.Class.classForName(Native Method)
                                                                         at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                                         at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                                         at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                                         		... 13 more
                                                                      Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available

**Comment by XiuLin** [comment]
按照正确的wiki构建流程进行
