### ISSUE TITLE
【必现】运行VirtualAPK，加载插件后退出，再次打开VirtualAPK时崩溃

### ISSUE THREAD

**Issue by HERHERMES** [didi/VirtualAPK#66]
现象描述：运行VirtualAPK, 点击加载插件，插件运行正常，返回键退出VirtualAPK，再次点击打开VirtualAPK，崩溃退出，报如下错误：
`11:37:56.168 11552-11552/com.didi.virtualapk E/AndroidRuntime: FATAL EXCEPTION: main
                                                                     Process: com.didi.virtualapk, PID: 11552
                                                                     java.lang.RuntimeException: Unable to start activity ComponentInfo{com.didi.virtualapk/com.didi.virtualapk.MainActivity}: android.view.InflateException: Binary XML file line #36: Error inflating class <unknown>
                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2664)
                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2733)
                                                                         at android.app.ActivityThread.access$900(ActivityThread.java:187)
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1584)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:111)
                                                                         at android.os.Looper.loop(Looper.java:194)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5877)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at java.lang.reflect.Method.invoke(Method.java:372)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1019)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:814)
                                                                      Caused by: android.view.InflateException: Binary XML file line #36: Error inflating class <unknown>
                                                                         at android.view.LayoutInflater.createView(LayoutInflater.java:639)
                                                                         at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:749)
                                                                         at android.view.LayoutInflater.rInflate(LayoutInflater.java:812)
                                                                         at android.view.LayoutInflater.rInflate(LayoutInflater.java:815)
                                                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:510)
                                                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:420)
                                                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:371)
                                                                         at android.support.v7.app.AppCompatDelegateImplV7.ensureSubDecor(AppCompatDelegateImplV7.java:299)
                                                                         at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:246)
                                                                         at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:106)
                                                                         at com.didi.virtualapk.MainActivity.onCreate(MainActivity.java:28)
                                                                         at android.app.Activity.performCreate(Activity.java:6127)
                                                                         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1125)
                                                                         at com.didi.virtualapk.internal.VAInstrumentation.callActivityOnCreate(VAInstrumentation.java:141)
                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2617)
                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2733) 
                                                                         at android.app.ActivityThread.access$900(ActivityThread.java:187) 
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1584) 
                                                                         at android.os.Handler.dispatchMessage(Handler.java:111) 
                                                                         at android.os.Looper.loop(Looper.java:194) 
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5877) 
                                                                         at java.lang.reflect.Method.invoke(Native Method) 
                                                                         at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1019) 
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:814) 
                                                                      Caused by: java.lang.reflect.InvocationTargetException
                                                                         at java.lang.reflect.Constructor.newInstance(Native Method)
                                                                         at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
                                                                         at android.view.LayoutInflater.createView(LayoutInflater.java:613)
                                                                         at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:749) 
                                                                         at android.view.LayoutInflater.rInflate(LayoutInflater.java:812) 
                                                                         at android.view.LayoutInflater.rInflate(LayoutInflater.java:815) 
                                                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:510) 
                                                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:420) 
                                                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:371) 
                                                                         at android.support.v7.app.AppCompatDelegateImplV7.ensureSubDecor(AppCompatDelegateImplV7.java:299) 
                                                                         at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:246) 
                                                                         at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:106) 
                                                                         at com.didi.virtualapk.MainActivity.onCreate(MainActivity.java:28) 
                                                                         at android.app.Activity.performCreate(Activity.java:6127) 
                                                                         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1125) 
                                                                         at com.didi.virtualapk.internal.VAInstrumentation.callActivityOnCreate(VAInstrumentation.java:141) 
                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2617) 
                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2733) 
                                                                         at android.app.ActivityThread.access$900(ActivityThread.java:187) 
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1584) 
                                                                         at android.os.Handler.dispatchMessage(Handler.java:111) 
                                                                         at android.os.Looper.loop(Looper.java:194) 
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5877) 
                                                                         at java.lang.reflect.Method.invoke(Native Method) 
                                                                         at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1019) 
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:814) 
                                                                      Caused by: java.lang.UnsupportedOperationException: Can't convert to dimension: type=0x1
                                                                         at android.content.res.TypedArray.getDimensionPixelSize(TypedArray.java:572)
                                                                         at android.view.View.<init>(View.java:3873)
                                                                         at android.widget.ImageView.<init>(ImageView.java:139)
                                                                         at android.widget.ImageButton.<init>(ImageButton.java:86)
                                                                         at android.widget.ImageButton.<init>(ImageButton.java:82)
                                                                         at android.support.v7.widget.Toolbar.ensureNavButtonView(Toolbar.java:990)
                                                                         at android.support.v7.widget.Toolbar.setNavigationContentDescription(Toolbar.java:731)
                                                                         at android.support.v7.widget.Toolbar.<init>(Toolbar.java:271)
                                                                         at android.support.v7.widget.Toolbar.<init>(Toolbar.java:191)
                                                                         at java.lang.reflect.Constructor.newInstance(Native Method) 
                                                                         at java.lang.reflect.Constructor.newInstance(Constructor.java:288) 
                                                                         at android.view.LayoutInflater.createView(LayoutInflater.java:613) 
                                                                         at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:749) 
                                                                         at android.view.LayoutInflater.rInflate(LayoutInflater.java:812) 
                                                                         at android.view.LayoutInflater.rInflate(LayoutInflater.java:815) 
                                                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:510) 
                                                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:420) 
                                                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:371) 
                                                                         at android.support.v7.app.AppCompatDelegateImplV7.ensureSubDecor(AppCompatDelegateImplV7.java:299) 
                                                                         at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:246) 
                                                                         at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:106) 
                                                                         at com.didi.virtualapk.MainActivity.onCreate(MainActivity.java:28) 
                                                                         at android.app.Activity.performCreate(Activity.java:6127) 
                                                                         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1125) 
                                                                         at com.didi.virtualapk.internal.VAInstrumentation.callActivityOnCreate(VAInstrumentation.java:141) 
                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2617) 
                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2733) 
                                                                         at android.app.ActivityThread.access$900(ActivityThread.java:187) 
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1584) 
                                                                         at android.os.Handler.dispatchMessage(Handler.java:111) 
                                                                         at android.os.Looper.loop(Looper.java:194) 
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5877) 
                                                                         at java.lang.reflect.Method.invoke(Native Method) 
                                                                         at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1019) 
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:814) `

**Comment by singwhatiwanna** [comment]
@HERHERMES [开发指南](https://github.com/didi/VirtualAPK/wiki/VirtualAPK-%E6%8F%92%E4%BB%B6%E5%BC%80%E5%8F%91%E6%8C%87%E5%8D%97)

**Comment by singwhatiwanna** [comment]
阅读四大组件相关的注意事项

**Comment by HERHERMES** [comment]
thx
