### ISSUE TITLE
编译插件数据越界，VAPlug in.groovy:188这是哪里的文件啊

### ISSUE THREAD

**Issue by malick-aiqi** [didi/VirtualAPK#68]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 2
        at com.didi.virtualapk.VAPlugin$_pickSplitEntries_closure8.doCall(VAPlug
in.groovy:188)
        at com.didi.virtualapk.VAPlugin.pickSplitEntries(VAPlugin.groovy:186)
        at com.didi.virtualapk.VAPlugin$_apply_closure1$_closure16.doCall(VAPlug
in.groovy:66)
        at com.didi.virtualapk.VAPlugin$_apply_closure1.doCall(VAPlugin.groovy:5
2)
        at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(Cl
osureBackedMethodInvocationDispatch.java:40)
        at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(Cl
osureBackedMethodInvocationDispatch.java:25)
        at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(Abstract
BroadcastDispatch.java:44)
        at org.gradle.internal.event.BroadcastDispatch.dispatch(BroadcastDispatc
h.java:79)
        at org.gradle.internal.event.BroadcastDispatch.dispatch(BroadcastDispatc
h.java:30)
        at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocati
onHandler.invoke(ProxyDispatchAdapter.java:93)
        at com.sun.proxy.$Proxy11.afterEvaluate(Unknown Source)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfte
rEvaluate(LifecycleProjectEvaluator.java:67)
        ... 52 more

**Comment by Gundam0079** [comment]
我也碰到这个问题 等待解决

**Comment by singwhatiwanna** [comment]
一般是插件工程和宿主工程协作出现了问题，我们准备写一篇文章专门讲述这个问题。

**Comment by lvmengyin** [comment]
什么时候才能解决这个问题啊？

**Comment by singwhatiwanna** [comment]
@malick-aiqi [常见问题解答](https://github.com/didi/VirtualAPK/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98%E8%A7%A3%E7%AD%94)
