### ISSUE TITLE
在编译plugin项目时候遇到这个错

### ISSUE THREAD

**Issue by Gundam0079** [didi/VirtualAPK#71]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 2
        at com.didi.virtualapk.VAPlugin$_pickSplitEntries_closure8.doCall(VAPlugin.groovy:188)
        at com.didi.virtualapk.VAPlugin.pickSplitEntries(VAPlugin.groovy:186)
        at com.didi.virtualapk.VAPlugin$_apply_closure1$_closure16.doCall(VAPlugin.groovy:66)
        at com.didi.virtualapk.VAPlugin$_apply_closure1.doCall(VAPlugin.groovy:52)
        at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:40)
        at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:25)
        at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:44)
        at org.gradle.internal.event.BroadcastDispatch.dispatch(BroadcastDispatch.java:79)
        at org.gradle.internal.event.BroadcastDispatch.dispatch(BroadcastDispatch.java:30)
        at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
        at com.sun.proxy.$Proxy10.afterEvaluate(Unknown Source)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfterEvaluate(LifecycleProjectEvaluator.java:67)
        ... 65 more

已经编译过宿主项目 然后用./gradlew clean assemblePlugin --stacktrace --info编译plugin项目 报上面的错 确认过gradle 2.14.1   tools   com.android.tools.build:gradle:2.1.3
QQ 215863169

**Comment by XiuLin** [comment]
这个时候去查看一下 插件工程中的gradle文件，其中可能会是compile处的问题
如果写成
compile(name: 'xxx-release', ext: 'aar')
请改成：
compile(name:'xxx', ext: 'aar')
宿主和插件工程都要修改

**Comment by singwhatiwanna** [comment]
@Gundam0079 [](https://github.com/didi/VirtualAPK/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98%E8%A7%A3%E7%AD%94)
