### ISSUE TITLE
07-18 22:58:13.055 30709-30709/com.didi.virtualapk:daemon D/MSF.C.MsfStore: setSaveRootPath or loadConfig failed.java.lang.UnsatisfiedLinkError: No implementation found for void com.tencent.qalsdk.config

### ISSUE THREAD

**Issue by tyoli** [didi/VirtualAPK#78]
07-18 22:58:13.054 30709-30709/com.didi.virtualapk:daemon E/art: No implementation found for void com.tencent.qalsdk.config.NativeConfigStore.setSaveRootPath(java.lang.String) (tried Java_com_tencent_qalsdk_config_NativeConfigStore_setSaveRootPath and Java_com_tencent_qalsdk_config_NativeConfigStore_setSaveRootPath__Ljava_lang_String_2)
07-18 22:58:13.055 30709-30709/com.didi.virtualapk:daemon D/MSF.C.MsfStore: setSaveRootPath or loadConfig failed.java.lang.UnsatisfiedLinkError: No implementation found for void com.tencent.qalsdk.config.NativeConfigStore.setSaveRootPath(java.lang.String) (tried Java_com_tencent_qalsdk_config_NativeConfigStore_setSaveRootPath and Java_com_tencent_qalsdk_config_NativeConfigStore_setSaveRootPath__Ljava_lang_String_2)
                                                                            java.lang.UnsatisfiedLinkError: No implementation found for void com.tencent.qalsdk.config.NativeConfigStore.setSaveRootPath(java.lang.String) (tried Java_com_tencent_qalsdk_config_NativeConfigStore_setSaveRootPath and Java_com_tencent_qalsdk_config_NativeConfigStore_setSaveRootPath__Ljava_lang_String_2)
                                                                                at com.tencent.qalsdk.config.NativeConfigStore.setSaveRootPath(Native Method)
                                                                                at com.tencent.qalsdk.core.l.a(MsfStore.java:38)
                                                                                at com.tencent.qalsdk.core.j.a(MsfCore.java:140)
                                                                                at com.tencent.qalsdk.service.QalService.serviceInit(QalService.java:278)
                                                                                at com.tencent.qalsdk.service.QalService.onCreate(QalService.java:223)
                                                                                at com.didi.virtualapk.delegate.LocalService.onStartCommand(LocalService.java:104)
                                                                                at com.didi.virtualapk.delegate.RemoteService.onStartCommand(RemoteService.java:58)
                                                                                at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3324)
                                                                                at android.app.ActivityThread.-wrap19(ActivityThread.java)
                                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1693)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:111)
                                                                                at android.os.Looper.loop(Looper.java:207)
                                                                                at android.app.ActivityThread.main(ActivityThread.java:5966)
                                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:749)
07-18 22:58:13.056 30709-30709/com.didi.virtualapk:daemon E/MSF.C.MsfCore: MsfStore init fail,so init:false
07-18 22:58:13.056 30709-30709/com.didi.virtualapk:daemon E/art: No implementation found for java.lang.String[] com.tencent.qalsdk.config.NativeConfigStore.getConfigList(java.lang.String) (tried Java_com_tencent_qalsdk_config_NativeConfigStore_getConfigList and Java_com_tencent_qalsdk_config_NativeConfigStore_getConfigList__Ljava_lang_String_2)
07-18 22:58:13.056 30709-30709/com.didi.virtualapk:daemon E/MSF.S.AppProcessManager: so init error:No implementation found for java.lang.String[] com.tencent.qalsdk.config.NativeConfigStore.getConfigList(java.lang.String) (tried Java_com_tencent_qalsdk_config_NativeConfigStore_getConfigList and Java_com_tencent_qalsdk_config_NativeConfigStore_getConfigList__Ljava_lang_String_2)
07-18 22:58:13.061 30709-30709/com.didi.virtualapk:daemon D/QalService: serivce onStart

**Comment by singwhatiwanna** [comment]
参考 [常见问题解答](https://github.com/didi/VirtualAPK/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98%E8%A7%A3%E7%AD%94)
