### ISSUE TITLE
Performing stop of activity that is not resumed: {com.didi.virtualapk/com.didi.virtualapk.MainActivity}                                                                      java.lang.RuntimeException: Performing stop of activity that is not resumed: {com.didi.virtualapk/com.didi.virtualapk.MainActivity

### ISSUE THREAD

**Issue by lypandroidex** [didi/VirtualAPK#84]
07-23 22:54:45.004 14302-14302/com.didi.virtualapk E/ActivityThread: Performing stop of activity that is not resumed: {com.didi.virtualapk/com.didi.virtualapk.MainActivity}
                                                                     java.lang.RuntimeException: Performing stop of activity that is not resumed: {com.didi.virtualapk/com.didi.virtualapk.MainActivity}
                                                                         at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:3496)
                                                                         at android.app.ActivityThread.handleStopActivity(ActivityThread.java:3577)
                                                                         at android.app.ActivityThread.access$1200(ActivityThread.java:160)
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1437)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                         at android.os.Looper.loop(Looper.java:179)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5491)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at java.lang.reflect.Method.invoke(Method.java:372)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:961)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)

**Comment by superqiaopu** [comment]
https://github.com/didi/VirtualAPK/wiki/%E6%8F%90%E9%97%AE%E5%BF%85%E7%9C%8B
