### ISSUE TITLE
宿主Apk无法打开插件apk

### ISSUE THREAD

**Issue by gongxm0412** [didi/VirtualAPK#93]
java.lang.RuntimeException: can not find ComponentInfo{com.example.xmgong.virturedemosub/com.example.xmgong.virturedemosub.HostMainActivity}

插件Apk代码
![](http://ww4.sinaimg.cn/large/006tKfTcgy1fhzk7fd676j30pe0codhx.jpg)
宿主Apk代码
 Intent intent = new Intent();
            intent.setClassName("com.example.xmgong.virturedemosub", "com.example.xmgong.virturedemosub.HostMainActivity");
            startActivity(intent);

**Comment by gongxm0412** [comment]
宿主Apk loadPlug 能成功

**Comment by gongxm0412** [comment]
宿主Apk 打开插件Apk代码
```
 Intent intent = new Intent();
            intent.setClassName("com.example.xmgong.virturedemosub", "com.example.xmgong.virturedemosub.MainActivity");
            startActivity(intent);
```

**Comment by gongxm0412** [comment]
完整的错误信息
```
  java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.xmgong.vituredemo/com.didi.virtualapk.core.A$1}: android.view.InflateException: Binary XML file line #93: Binary XML file line #93: Error inflating class <unknown>
                                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2793)
                                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2864)
                                                                                   at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1567)
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                                   at android.os.Looper.loop(Looper.java:156)
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:6523)
                                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)
                                                                                Caused by: android.view.InflateException: Binary XML file line #93: Binary XML file line #93: Error inflating class <unknown>
                                                                                Caused by: android.view.InflateException: Binary XML file line #93: Error inflating class <unknown>
                                                                           
```
