### ISSUE TITLE
You need to use a Theme.AppCompat theme

### ISSUE THREAD

**Issue by BeEagle** [didi/VirtualAPK#94]
Process: com.didi.virtualapk, PID: 16515
                                                                     java.lang.RuntimeException: Unable to start activity ComponentInfo{com.didi.virtualapk/com.didi.virtualapk.core.A$1}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2454)
                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2516)
                                                                         at android.app.ActivityThread.access$1200(ActivityThread.java:163)
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1374)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                         at android.os.Looper.loop(Looper.java:135)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5601)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at java.lang.reflect.Method.invoke(Method.java:372)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759)
                                                                      Caused by: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
                                                                         at android.support.v7.app.AppCompatDelegateImplBase.onCreate(AppCompatDelegateImplBase.java:122)
                                                                         at android.support.v7.app.AppCompatDelegateImplV7.onCreate(AppCompatDelegateImplV7.java:146)
                                                                         at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:59)
                                                                         at com.didi.virtualapk.demo.aidl.BookManagerActivity.onCreate(BookManagerActivity.java:95)
                                                                         at android.app.Activity.performCreate(Activity.java:6100)
                                                                         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1109)
                                                                         at com.didi.virtualapk.internal.VAInstrumentation.callActivityOnCreate(VAInstrumentation.java:141)
                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2407)
                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2516) 
                                                                         at android.app.ActivityThread.access$1200(ActivityThread.java:163) 
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1374) 
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                         at android.os.Looper.loop(Looper.java:135) 
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5601) 
                                                                         at java.lang.reflect.Method.invoke(Native Method) 
                                                                         at java.lang.reflect.Method.invoke(Method.java:372)

**Comment by lypandroidex** [comment]
这个主题报错的话，我换成和demo一样的版本编译就OK了，
可能是25的版本不兼容导致的。


李永平





公司：深圳市安卓工控设备有限公司
邮箱：liyp@androidex.cn
电话：17737331085


请关注微信公众账号：




原始邮件
发件人:BeEaglenotifications@github.com
收件人:didi/VirtualAPKVirtualAPK@noreply.github.com
抄送:Subscribedsubscribed@noreply.github.com
发送时间:2017年7月28日(周五) 14:38
主题:[didi/VirtualAPK] You need to use a Theme.AppCompat theme (#94)


Process: com.didi.virtualapk, PID: 16515
 java.lang.RuntimeException: Unable to start activity ComponentInfo{com.didi.virtualapk/com.didi.virtualapk.core.A$1}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2454)
 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2516)
 at android.app.ActivityThread.access$1200(ActivityThread.java:163)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1374)
 at android.os.Handler.dispatchMessage(Handler.java:102)
 at android.os.Looper.loop(Looper.java:135)
 at android.app.ActivityThread.main(ActivityThread.java:5601)
 at java.lang.reflect.Method.invoke(Native Method)
 at java.lang.reflect.Method.invoke(Method.java:372)
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759)
 Caused by: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
 at android.support.v7.app.AppCompatDelegateImplBase.onCreate(AppCompatDelegateImplBase.java:122)
 at android.support.v7.app.AppCompatDelegateImplV7.onCreate(AppCompatDelegateImplV7.java:146)
 at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:59)
 at com.didi.virtualapk.demo.aidl.BookManagerActivity.onCreate(BookManagerActivity.java:95)
 at android.app.Activity.performCreate(Activity.java:6100)
 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1109)
 at com.didi.virtualapk.internal.VAInstrumentation.callActivityOnCreate(VAInstrumentation.java:141)
 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2407)
 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2516)
 at android.app.ActivityThread.access$1200(ActivityThread.java:163)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1374)
 at android.os.Handler.dispatchMessage(Handler.java:102)
 at android.os.Looper.loop(Looper.java:135)
 at android.app.ActivityThread.main(ActivityThread.java:5601)
 at java.lang.reflect.Method.invoke(Native Method)
 at java.lang.reflect.Method.invoke(Method.java:372)

**Comment by BeEagle** [comment]
出问题的就是clone 的DEMO ，怎么回事？

**Comment by fendouwangzi** [comment]
我这里也是出现同样的错误，今天下载的。
在两个手机上试了，同样的问题。单独运行插件apk没问题
手机是魅族mx5 5.1，  华为荣耀8青春版,7.0

**Comment by fendouwangzi** [comment]
需要把targetHost = '../app' 这样改。
