### ISSUE TITLE
android.content.res.Resources$NotFoundException: File res/mipmap-xxhdpi-v4/ic_launcher.png from xml type layout resource ID #0x7f030000

### ISSUE THREAD

**Issue by BeEagle** [didi/VirtualAPK#95]
Process: com.troy.vahostdemo, PID: 2606
                                                                   java.lang.RuntimeException: Unable to start activity ComponentInfo{com.troy.vahostdemo/com.didi.virtualapk.core.A$1}: android.content.res.Resources$NotFoundException: File res/mipmap-xxhdpi-v4/ic_launcher.png from xml type layout resource ID #0x7f030000
                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2454)
                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2516)
                                                                       at android.app.ActivityThread.access$1200(ActivityThread.java:163)
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1374)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                       at android.os.Looper.loop(Looper.java:135)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5601)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at java.lang.reflect.Method.invoke(Method.java:372)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759)
                                                                    Caused by: android.content.res.Resources$NotFoundException: File res/mipmap-xxhdpi-v4/ic_launcher.png from xml type layout resource ID #0x7f030000
                                                                       at android.content.res.Resources.loadXmlResourceParser(Resources.java:2887)
                                                                       at android.content.res.Resources.loadXmlResourceParser(Resources.java:2842)
                                                                       at android.content.res.Resources.getLayout(Resources.java:1131)
                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:422)
                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:368)
                                                                       at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:292)
                                                                       at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
                                                                       at com.troy.vaplugindemo.MainActivity.onCreate(MainActivity.java:23)
                                                                       at android.app.Activity.performCreate(Activity.java:6100)
                                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1109)
                                                                       at com.didi.virtualapk.internal.VAInstrumentation.callActivityOnCreate(VAInstrumentation.java:141)
                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2407)
                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2516) 
                                                                       at android.app.ActivityThread.access$1200(ActivityThread.java:163) 
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1374) 
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                       at android.os.Looper.loop(Looper.java:135) 
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5601) 
                                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                                       at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964) 
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759) 
                                                                    Caused by: java.io.FileNotFoundException: Corrupt XML binary file
                                                                       at android.content.res.AssetManager.openXmlAssetNative(Native Method)
                                                                       at android.content.res.AssetManager.openXmlBlockAsset(AssetManager.java:485)
                                                                       at android.content.res.Resources.loadXmlResourceParser(Resources.java:2869)
                                                                       at android.content.res.Resources.loadXmlResourceParser(Resources.java:2842) 
                                                                       at android.content.res.Resources.getLayout(Resources.java:1131) 
                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:422) 
                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:368) 
                                                                       at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:292) 
                                                                       at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
                                                                       at com.troy.vaplugindemo.MainActivity.onCreate(MainActivity.java:23) 
                                                                       at android.app.Activity.performCreate(Activity.java:6100) 
                                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1109) 
                                                                       at com.didi.virtualapk.internal.VAInstrumentation.callActivityOnCreate(VAInstrumentation.java:141) 
                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2407) 
                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2516) 
                                                                       at android.app.ActivityThread.access$1200(ActivityThread.java:163) 
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1374) 
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                       at android.os.Looper.loop(Looper.java:135) 
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5601) 
                                                                       at java.lang.reflect.Method.invoke(Native Method)

**Comment by helloworldjie** [comment]
把mipmap改成drawable试试， 插件和宿主貌似都不支持mipmap， 把mipmap-hdpi/xhdpi/xxhdpi全部改成drawable-hdpi/xhdpi/xxhdpi，我这样弄就好了， 你也试试
